export type { ParsedRefTarget } from "@cosmicdrift/kumiko-framework/ui-types";
// Re-Export aus framework/ui-types damit Renderer-Code denselben
// Parser nutzt wie der Server-Boot-Validator (Cross-Feature-Refs).
export { parseRefTarget } from "@cosmicdrift/kumiko-framework/ui-types";
export type {
  AssetResolution,
  AssetResolveContext,
  AssetResolver,
  BadgeProps,
  ButtonProps,
  CardProps,
  DatePickerProps,
  IconProps,
  LocaleResolver,
  ModalProps,
  NumberInputProps,
  PrimitiveCommonProps,
  PrimitivesContract,
  SelectOption,
  SelectProps,
  TextInputProps,
  ToastIntent,
  ToastProps,
  ToggleProps,
} from "./contracts/index.js";
export type {
  BatchResult,
  Command,
  Dispatcher,
  DispatcherError,
  DispatcherStatus,
  FieldIssue,
  PendingFile,
  PendingWrite,
  QueryOpts,
  QueryResult,
  StreamOpts,
  WriteOpts,
  WriteResult,
} from "./dispatcher/index.js";
export { StreamFrame, type StreamFrameEvent } from "./dispatcher/index.js";
export type {
  FieldConditionPredicate,
  FieldConditions,
  FieldConditionValue,
  FieldState,
  FormController,
  FormControllerOptions,
  FormSnapshot,
  FormValues,
  SubmitConfig,
  SubmitPayloadMode,
  SubmitResult,
} from "./form/index.js";
export {
  createFormController,
  I18N_KEY_PARAM,
  relevantFieldIssues,
  zodErrorToFieldIssues,
} from "./form/index.js";
export {
  applyFormatSpec,
  currencyDecimals,
  escapeHtml,
  escapeHtmlAttr,
  escapeXml,
  type HtmlValue,
  html,
  isSafeHref,
  RawHtml,
  raw,
  stripControlChars,
  toInstant,
} from "./format/index.js";
export type {
  NavDefinition,
  NavNode,
  NavRegistrySlice,
  NavTree,
  ResolveNavigationOptions,
} from "./nav/index.js";
export { resolveNavigation } from "./nav/index.js";
export type { Store, WritableStore } from "./store/index.js";
export { createStore, shallowEqual } from "./store/index.js";
export type {
  ComputeEditViewModelInput,
  ComputeListViewModelInput,
  DerivedCellRoundingTarget,
  EditExtensionSectionViewModel,
  EditFieldSpec,
  EditFieldsSectionViewModel,
  EditFieldViewModel,
  EditRelatedListSectionViewModel,
  EditSectionSpec,
  EditSectionViewModel,
  EditViewModel,
  EditWriteFormSectionViewModel,
  EmbeddedDerivedOp,
  EmbeddedListCellViewModel,
  EmbeddedListIssueGroups,
  FieldConditionCtx,
  FieldRenderer,
  ListColumnSpec,
  ListColumnViewModel,
  ListRowViewModel,
  ListViewModel,
  RuntimeRenderer,
  ScreenSlots,
  Translate,
} from "./view-model/index.js";
export {
  buildOptionLabels,
  computeDerivedCellValue,
  computeEditViewModel,
  computeListViewModel,
  computeRelatedListSectionViewModel,
  embeddedCellLabelKey,
  embeddedCellOptionLabelKey,
  fieldLabelKey,
  fieldOptionLabelKey,
  fieldOptionLabelKeyPrefix,
  groupEmbeddedListIssues,
  roundDerivedCellValue,
  sumEmbeddedListColumn,
} from "./view-model/index.js";
