-- Migration 0001_init
-- Generated: 2026-07-08T13:04:43.338Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_config_values" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "key" text NOT NULL,
  "value" text,
  "user_id" text
);
CREATE INDEX IF NOT EXISTS "read_config_values_tenant_id_idx" ON "read_config_values" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_config_values_unique" ON "read_config_values" ("key", "tenant_id", "user_id");

CREATE TABLE IF NOT EXISTS "read_delivery_attempts" (
  "id" uuid PRIMARY KEY,
  "tenant_id" uuid NOT NULL,
  "notification_type" text NOT NULL,
  "channel" text NOT NULL,
  "recipient_id" text,
  "recipient_address" text,
  "status" text NOT NULL,
  "error" text,
  "priority" text DEFAULT 'normal' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "read_download_attempts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "result" text NOT NULL,
  "via" text NOT NULL,
  "token_hash" text,
  "job_id" text,
  "attempted_by_user_id" text,
  "ip" text,
  "user_agent" text,
  "attempted_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_download_attempts_tenant_id_idx" ON "read_download_attempts" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_export_download_tokens" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "job_id" text NOT NULL,
  "token_hash" text NOT NULL,
  "issued_at" timestamp with time zone NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "last_used_at" timestamp with time zone,
  "use_count" bigint,
  "last_used_from_ip" text,
  "last_used_user_agent" text
);
CREATE INDEX IF NOT EXISTS "read_export_download_tokens_tenant_id_idx" ON "read_export_download_tokens" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_export_download_tokens_one_per_job" ON "read_export_download_tokens" ("job_id");

CREATE TABLE IF NOT EXISTS "read_export_jobs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "requested_from_tenant_id" text NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "requested_at" timestamp with time zone NOT NULL,
  "started_at" timestamp with time zone,
  "completed_at" timestamp with time zone,
  "download_storage_key" text,
  "expires_at" timestamp with time zone,
  "error_message" text,
  "bytes_written" bigint
);
CREATE INDEX IF NOT EXISTS "read_export_jobs_tenant_id_idx" ON "read_export_jobs" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_export_jobs_one_active_per_user" ON "read_export_jobs" ("user_id") WHERE status IN ('pending', 'running');

CREATE TABLE IF NOT EXISTS "read_notification_preferences" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "notification_type" text NOT NULL,
  "channel" text NOT NULL,
  "enabled" boolean DEFAULT true NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "read_notification_preferences_unique" ON "read_notification_preferences" ("tenant_id", "user_id", "notification_type", "channel");

CREATE TABLE IF NOT EXISTS "read_tasks" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "title" text NOT NULL,
  "status" text,
  "priority" integer,
  "is_urgent" boolean DEFAULT false NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tasks_tenant_id_idx" ON "read_tasks" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_tenant_compliance_profiles" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "profile_key" text NOT NULL,
  "override" text
);
CREATE INDEX IF NOT EXISTS "read_tenant_compliance_profiles_tenant_id_idx" ON "read_tenant_compliance_profiles" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_compliance_profiles_tenant_id_unique" ON "read_tenant_compliance_profiles" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_tenant_invitations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "email" text NOT NULL,
  "email_bidx" text,
  "role" text NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "invited_by" text NOT NULL,
  "expires_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tenant_invitations_tenant_id_idx" ON "read_tenant_invitations" ("tenant_id");
CREATE INDEX IF NOT EXISTS "read_tenant_invitations_email_bidx_idx" ON "read_tenant_invitations" ("email_bidx");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_invitations_tenant_email_unique" ON "read_tenant_invitations" ("tenant_id", "email");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_invitations_tenant_email_unique_bidx" ON "read_tenant_invitations" ("tenant_id", "email_bidx") WHERE "email_bidx" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "read_tenant_memberships" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "roles" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tenant_memberships_tenant_id_idx" ON "read_tenant_memberships" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_memberships_unique" ON "read_tenant_memberships" ("user_id", "tenant_id");

CREATE TABLE IF NOT EXISTS "read_tenant_retention_overrides" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "entity_name" text NOT NULL,
  "config" text NOT NULL,
  "reason" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tenant_retention_overrides_tenant_id_idx" ON "read_tenant_retention_overrides" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_retention_overrides_tenant_id_entity_name_unique" ON "read_tenant_retention_overrides" ("tenant_id", "entity_name");

CREATE TABLE IF NOT EXISTS "read_tenant_secrets" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "key" text NOT NULL,
  "envelope" jsonb NOT NULL,
  "kek_version" integer NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "last_rotated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_secrets_tenant_key_unique" ON "read_tenant_secrets" ("tenant_id", "key");

CREATE TABLE IF NOT EXISTS "read_tenants" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "key" text NOT NULL,
  "name" text NOT NULL,
  "is_enabled" boolean DEFAULT true NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "destroy_requested_at" timestamp with time zone,
  "destroy_requested_by" text,
  "grace_period_end" timestamp with time zone,
  "destroy_started_at" timestamp with time zone,
  "destroyed_at" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "read_tenants_tenant_id_idx" ON "read_tenants" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenants_key_unique" ON "read_tenants" ("key");

CREATE TABLE IF NOT EXISTS "read_user_sessions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" text NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "revoked_at" timestamp with time zone,
  "ip" text,
  "user_agent" text
);
CREATE INDEX IF NOT EXISTS "read_user_sessions_tenant_id_idx" ON "read_user_sessions" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "deleted_at" timestamp with time zone,
  "deleted_by_id" text,
  "email" text NOT NULL,
  "email_bidx" text,
  "password_hash" text,
  "display_name" text NOT NULL,
  "locale" text DEFAULT 'de',
  "last_active_tenant_id" text,
  "email_verified" boolean DEFAULT false NOT NULL,
  "roles" text DEFAULT '[]' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "grace_period_end" timestamp with time zone,
  "pending_deletion_request_id" text
);
CREATE INDEX IF NOT EXISTS "read_users_tenant_id_idx" ON "read_users" ("tenant_id");
CREATE INDEX IF NOT EXISTS "read_users_email_bidx_idx" ON "read_users" ("email_bidx");
