-- Migration 0002_catch-up-entity-schema-drift
-- Generated: 2026-08-20T13:59:24.692Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "store_delivery_attempts" (
  "id" uuid PRIMARY KEY,
  "tenant_id" uuid NOT NULL,
  "notification_type" text NOT NULL,
  "channel" text NOT NULL,
  "recipient_id" text,
  "recipient_address" text,
  "status" text NOT NULL,
  "error" text,
  "priority" text DEFAULT 'normal' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "store_user_sessions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" text NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "revoked_at" timestamp with time zone,
  "last_seen_at" timestamp with time zone,
  "ip" text,
  "user_agent" text
);
CREATE INDEX IF NOT EXISTS "store_user_sessions_tenant_id_idx" ON "store_user_sessions" ("tenant_id");

-- === Changed tables ===
-- read_tasks
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
-- WARN: destructive change (column type change: priority) forces DROP+CREATE + full event replay.
-- Consider an Expand/Contract split across two releases to avoid the rebuild — see docs/guides/expand-contract-managed-projections.md.
DROP TABLE IF EXISTS "read_tasks";
CREATE TABLE IF NOT EXISTS "read_tasks" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "title" text NOT NULL,
  "status" text,
  "priority" double precision,
  "is_urgent" boolean DEFAULT false NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tasks_tenant_id_idx" ON "read_tasks" ("tenant_id");

-- read_tenant_invitations
ALTER TABLE "read_tenant_invitations" ADD COLUMN "invited_by_bidx" text;
CREATE INDEX IF NOT EXISTS "read_tenant_invitations_invited_by_bidx_idx" ON "read_tenant_invitations" ("invited_by_bidx");

-- read_users
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
-- WARN: destructive change (new UNIQUE index(es): read_users_email_unique, read_users_email_unique_bidx) forces DROP+CREATE + full event replay.
-- Consider an Expand/Contract split across two releases to avoid the rebuild — see docs/guides/expand-contract-managed-projections.md.
DROP TABLE IF EXISTS "read_users";
CREATE TABLE IF NOT EXISTS "read_users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "deleted_at" timestamp with time zone,
  "deleted_by_id" text,
  "email" text NOT NULL,
  "email_bidx" text,
  "password_hash" text,
  "display_name" text NOT NULL,
  "display_name_bidx" text,
  "locale" text,
  "timezone" text,
  "last_active_tenant_id" text,
  "email_verified" boolean DEFAULT false NOT NULL,
  "roles" text DEFAULT '[]' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "grace_period_end" timestamp with time zone,
  "pending_deletion_request_id" text
);
CREATE INDEX IF NOT EXISTS "read_users_tenant_id_idx" ON "read_users" ("tenant_id");
CREATE INDEX IF NOT EXISTS "read_users_email_bidx_idx" ON "read_users" ("email_bidx");
CREATE INDEX IF NOT EXISTS "read_users_display_name_bidx_idx" ON "read_users" ("display_name_bidx");
CREATE UNIQUE INDEX IF NOT EXISTS "read_users_email_unique" ON "read_users" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "read_users_email_unique_bidx" ON "read_users" ("email_bidx") WHERE "email_bidx" IS NOT NULL;

-- === Dropped tables ===
-- DESTRUCTIVE: DROP TABLE IF EXISTS "read_delivery_attempts";  -- uncomment + ensure backup + run during maintenance window
-- DESTRUCTIVE: DROP TABLE IF EXISTS "read_user_sessions";  -- uncomment + ensure backup + run during maintenance window
