-- Migration 0006_fix-users-email-unique-soft-delete-predicate
-- Generated: 2026-09-11T08:10:23.072Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_users
-- index "read_users_email_unique" changed (where <none> → "is_deleted" = false) — recreated
DROP INDEX IF EXISTS "read_users_email_unique";
CREATE UNIQUE INDEX IF NOT EXISTS "read_users_email_unique" ON "read_users" ("email") WHERE "is_deleted" = false;
