-- Migration 0011_add-invitation-membership-version
-- Generated: 2026-10-09T14:23:30.731Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_tenant_invitations
ALTER TABLE "read_tenant_invitations" ADD COLUMN "membership_version" integer;
