-- Migration 0001_init
-- Generated: 2026-07-26T04:29:37.291Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "file_refs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "deleted_at" timestamp with time zone,
  "deleted_by_id" text,
  "storage_key" text NOT NULL,
  "file_name" text NOT NULL,
  "mime_type" text NOT NULL,
  "size" bigint NOT NULL,
  "entity_type" text,
  "entity_id" text,
  "field_name" text
);
CREATE INDEX IF NOT EXISTS "file_refs_tenant_id_idx" ON "file_refs" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_cap_counters" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "cap_name" text NOT NULL,
  "value" bigint DEFAULT 0 NOT NULL,
  "period_start" timestamp with time zone NOT NULL,
  "last_soft_warned_at" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "read_cap_counters_tenant_id_idx" ON "read_cap_counters" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_config_values" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "key" text NOT NULL,
  "value" text,
  "user_id" text
);
CREATE INDEX IF NOT EXISTS "read_config_values_tenant_id_idx" ON "read_config_values" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_config_values_unique" ON "read_config_values" ("key", "tenant_id", "user_id");

CREATE TABLE IF NOT EXISTS "read_custom_field_definitions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "deleted_at" timestamp with time zone,
  "deleted_by_id" text,
  "entity_name" text NOT NULL,
  "field_key" text NOT NULL,
  "type" text NOT NULL,
  "required" boolean DEFAULT false NOT NULL,
  "searchable" boolean DEFAULT false NOT NULL,
  "display_order" integer NOT NULL,
  "serialized_field" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_custom_field_definitions_tenant_id_idx" ON "read_custom_field_definitions" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_document_extracts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "file_ref_id" text NOT NULL,
  "storage_key" text NOT NULL,
  "pages" text,
  "meta" jsonb DEFAULT '{}'::jsonb NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_document_extracts_tenant_id_idx" ON "read_document_extracts" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_download_attempts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "result" text NOT NULL,
  "via" text NOT NULL,
  "token_hash" text,
  "job_id" text,
  "attempted_by_user_id" text,
  "ip" text,
  "user_agent" text,
  "attempted_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_download_attempts_tenant_id_idx" ON "read_download_attempts" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_export_download_tokens" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "job_id" text NOT NULL,
  "token_hash" text NOT NULL,
  "issued_at" timestamp with time zone NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "last_used_at" timestamp with time zone,
  "use_count" bigint,
  "last_used_from_ip" text,
  "last_used_user_agent" text
);
CREATE INDEX IF NOT EXISTS "read_export_download_tokens_tenant_id_idx" ON "read_export_download_tokens" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_export_download_tokens_one_per_job" ON "read_export_download_tokens" ("job_id");

CREATE TABLE IF NOT EXISTS "read_export_jobs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "requested_from_tenant_id" text NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "requested_at" timestamp with time zone NOT NULL,
  "started_at" timestamp with time zone,
  "completed_at" timestamp with time zone,
  "download_storage_key" text,
  "expires_at" timestamp with time zone,
  "error_message" text,
  "bytes_written" bigint
);
CREATE INDEX IF NOT EXISTS "read_export_jobs_tenant_id_idx" ON "read_export_jobs" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_export_jobs_one_active_per_user" ON "read_export_jobs" ("user_id") WHERE status IN ('pending', 'running');

CREATE TABLE IF NOT EXISTS "read_folder_assignments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "deleted_at" timestamp with time zone,
  "deleted_by_id" text,
  "folder_id" text NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_folder_assignments_tenant_id_idx" ON "read_folder_assignments" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_folders" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "name" text NOT NULL,
  "parent_id" text
);
CREATE INDEX IF NOT EXISTS "read_folders_tenant_id_idx" ON "read_folders" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_inbound_messages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "account_id" text NOT NULL,
  "owner_user_id" text,
  "message_id_header" text NOT NULL,
  "thread_key" text NOT NULL,
  "from" text NOT NULL,
  "to" text,
  "cc" text,
  "subject" text,
  "snippet" text,
  "received_at" timestamp with time zone NOT NULL,
  "body_ref" text,
  "scope" text
);
CREATE INDEX IF NOT EXISTS "read_inbound_messages_tenant_id_idx" ON "read_inbound_messages" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_job_runs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "job_name" text NOT NULL,
  "bull_job_id" text NOT NULL,
  "status" text NOT NULL,
  "payload" text,
  "error" text,
  "attempt" integer DEFAULT 1 NOT NULL,
  "started_at" timestamp with time zone NOT NULL,
  "finished_at" timestamp with time zone,
  "duration" integer,
  "triggered_by_id" text
);
CREATE INDEX IF NOT EXISTS "read_job_runs_tenant_id_idx" ON "read_job_runs" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_ledger_accounts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "name" text NOT NULL,
  "type" text NOT NULL,
  "code" text,
  "parent_id" text
);
CREATE INDEX IF NOT EXISTS "read_ledger_accounts_tenant_id_idx" ON "read_ledger_accounts" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_ledger_schedules" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "description" text NOT NULL,
  "start_date" timestamp with time zone NOT NULL,
  "end_date" timestamp with time zone,
  "interval" text NOT NULL,
  "amount" integer NOT NULL,
  "debit_account_id" text NOT NULL,
  "credit_account_id" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_ledger_schedules_tenant_id_idx" ON "read_ledger_schedules" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_ledger_transactions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "date" timestamp with time zone NOT NULL,
  "description" text NOT NULL,
  "reference" text,
  "status" text NOT NULL,
  "lines" jsonb DEFAULT '{}'::jsonb NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_ledger_transactions_tenant_id_idx" ON "read_ledger_transactions" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_mail_accounts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "provider" text NOT NULL,
  "auth_method" text NOT NULL,
  "owner_user_id" text,
  "display_name" text,
  "address" text NOT NULL,
  "status" text NOT NULL,
  "watch_state" text,
  "connected_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_mail_accounts_tenant_id_idx" ON "read_mail_accounts" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_mail_threads" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "thread_key" text NOT NULL,
  "subject" text,
  "last_message_at" timestamp with time zone NOT NULL,
  "message_count" integer NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_mail_threads_tenant_id_idx" ON "read_mail_threads" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_notification_preferences" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "notification_type" text NOT NULL,
  "channel" text NOT NULL,
  "enabled" boolean DEFAULT true NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "read_notification_preferences_unique" ON "read_notification_preferences" ("tenant_id", "user_id", "notification_type", "channel");

CREATE TABLE IF NOT EXISTS "read_pages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "slug" text NOT NULL,
  "lang" text NOT NULL,
  "title" text NOT NULL,
  "body" text,
  "description" text,
  "og_image" text,
  "published" boolean DEFAULT false NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_pages_tenant_id_idx" ON "read_pages" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_pages_unique" ON "read_pages" ("tenant_id", "slug", "lang");

CREATE TABLE IF NOT EXISTS "read_subscriptions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "provider_name" text NOT NULL,
  "provider_customer_id" text NOT NULL,
  "provider_subscription_id" text NOT NULL,
  "status" text NOT NULL,
  "tier" text NOT NULL,
  "current_period_end" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_subscriptions_tenant_id_idx" ON "read_subscriptions" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_tag_assignments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "deleted_at" timestamp with time zone,
  "deleted_by_id" text,
  "tag_id" text NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tag_assignments_tenant_id_idx" ON "read_tag_assignments" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_tags" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "name" text NOT NULL,
  "color" text,
  "scope" text
);
CREATE INDEX IF NOT EXISTS "read_tags_tenant_id_idx" ON "read_tags" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_template_resources" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "slug" text NOT NULL,
  "kind" text NOT NULL,
  "locale" text NOT NULL,
  "content" text,
  "content_format" text NOT NULL,
  "variable_schema" text,
  "linked_resources" text,
  "scope" text NOT NULL,
  "parent_template_id" text,
  "status" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_template_resources_tenant_id_idx" ON "read_template_resources" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_template_resources_unique" ON "read_template_resources" ("tenant_id", "slug", "kind", "locale");

CREATE TABLE IF NOT EXISTS "read_tenant_compliance_profiles" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "profile_key" text NOT NULL,
  "override" text
);
CREATE INDEX IF NOT EXISTS "read_tenant_compliance_profiles_tenant_id_idx" ON "read_tenant_compliance_profiles" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_compliance_profiles_tenant_id_unique" ON "read_tenant_compliance_profiles" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_tenant_invitations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "email" text NOT NULL,
  "email_bidx" text,
  "role" text NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "invited_by" text NOT NULL,
  "expires_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tenant_invitations_tenant_id_idx" ON "read_tenant_invitations" ("tenant_id");
CREATE INDEX IF NOT EXISTS "read_tenant_invitations_email_bidx_idx" ON "read_tenant_invitations" ("email_bidx");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_invitations_tenant_email_unique" ON "read_tenant_invitations" ("tenant_id", "email");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_invitations_tenant_email_unique_bidx" ON "read_tenant_invitations" ("tenant_id", "email_bidx") WHERE "email_bidx" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "read_tenant_memberships" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "roles" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tenant_memberships_tenant_id_idx" ON "read_tenant_memberships" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_memberships_unique" ON "read_tenant_memberships" ("user_id", "tenant_id");

CREATE TABLE IF NOT EXISTS "read_tenant_retention_overrides" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "entity_name" text NOT NULL,
  "config" text NOT NULL,
  "reason" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tenant_retention_overrides_tenant_id_idx" ON "read_tenant_retention_overrides" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_retention_overrides_tenant_id_entity_name_unique" ON "read_tenant_retention_overrides" ("tenant_id", "entity_name");

CREATE TABLE IF NOT EXISTS "read_tenant_secrets" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "key" text NOT NULL,
  "envelope" jsonb NOT NULL,
  "kek_version" integer NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "last_rotated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_secrets_tenant_key_unique" ON "read_tenant_secrets" ("tenant_id", "key");

CREATE TABLE IF NOT EXISTS "read_tenants" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "key" text NOT NULL,
  "name" text NOT NULL,
  "is_enabled" boolean DEFAULT true NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "destroy_requested_at" timestamp with time zone,
  "destroy_requested_by" text,
  "grace_period_end" timestamp with time zone,
  "destroy_started_at" timestamp with time zone,
  "destroyed_at" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "read_tenants_tenant_id_idx" ON "read_tenants" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenants_key_unique" ON "read_tenants" ("key");

CREATE TABLE IF NOT EXISTS "read_text_blocks" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "slug" text NOT NULL,
  "lang" text NOT NULL,
  "title" text NOT NULL,
  "body" text,
  "folder" text
);
CREATE INDEX IF NOT EXISTS "read_text_blocks_tenant_id_idx" ON "read_text_blocks" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_text_blocks_unique" ON "read_text_blocks" ("tenant_id", "slug", "lang");

CREATE TABLE IF NOT EXISTS "read_tier_assignments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "tier" text NOT NULL,
  "source" text
);
CREATE INDEX IF NOT EXISTS "read_tier_assignments_tenant_id_idx" ON "read_tier_assignments" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_user_mfa" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "totp_secret" text NOT NULL,
  "recovery_codes" text NOT NULL,
  "enabled_at" timestamp with time zone NOT NULL,
  "last_used_at" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "read_user_mfa_tenant_id_idx" ON "read_user_mfa" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_user_mfa_user_unique" ON "read_user_mfa" ("user_id", "tenant_id");

CREATE TABLE IF NOT EXISTS "read_users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "deleted_at" timestamp with time zone,
  "deleted_by_id" text,
  "email" text NOT NULL,
  "email_bidx" text,
  "password_hash" text,
  "display_name" text NOT NULL,
  "locale" text,
  "last_active_tenant_id" text,
  "email_verified" boolean DEFAULT false NOT NULL,
  "roles" text DEFAULT '[]' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "grace_period_end" timestamp with time zone,
  "pending_deletion_request_id" text
);
CREATE INDEX IF NOT EXISTS "read_users_tenant_id_idx" ON "read_users" ("tenant_id");
CREATE INDEX IF NOT EXISTS "read_users_email_bidx_idx" ON "read_users" ("email_bidx");

CREATE TABLE IF NOT EXISTS "store_api_tokens" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" text NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "name" text NOT NULL,
  "token_hash" text NOT NULL,
  "prefix" text NOT NULL,
  "scopes" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "expires_at" timestamp with time zone,
  "revoked_at" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "store_api_tokens_tenant_id_idx" ON "store_api_tokens" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "store_api_tokens_hash_unique" ON "store_api_tokens" ("token_hash");

CREATE TABLE IF NOT EXISTS "store_delivery_attempts" (
  "id" uuid PRIMARY KEY,
  "tenant_id" uuid NOT NULL,
  "notification_type" text NOT NULL,
  "channel" text NOT NULL,
  "recipient_id" text,
  "recipient_address" text,
  "status" text NOT NULL,
  "error" text,
  "priority" text DEFAULT 'normal' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "store_global_feature_state" (
  "feature_name" text PRIMARY KEY,
  "enabled" boolean NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_by" text
);

CREATE TABLE IF NOT EXISTS "store_job_run_logs" (
  "id" serial PRIMARY KEY,
  "run_id" text NOT NULL,
  "level" text NOT NULL,
  "message" text NOT NULL,
  "timestamp" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "store_mail_seen_messages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "account_id" text NOT NULL,
  "provider_message_id" text NOT NULL,
  "seen_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "store_mail_seen_messages_tenant_id_idx" ON "store_mail_seen_messages" ("tenant_id");

CREATE TABLE IF NOT EXISTS "store_mail_sync_cursors" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "account_id" text NOT NULL,
  "scope" text NOT NULL,
  "cursor" text NOT NULL,
  "updated_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "store_mail_sync_cursors_tenant_id_idx" ON "store_mail_sync_cursors" ("tenant_id");

CREATE TABLE IF NOT EXISTS "store_user_sessions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" text NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "revoked_at" timestamp with time zone,
  "ip" text,
  "user_agent" text
);
CREATE INDEX IF NOT EXISTS "store_user_sessions_tenant_id_idx" ON "store_user_sessions" ("tenant_id");
