-- Migration 0002_add_user_timezone
-- Generated: 2026-07-30T12:47:00.324Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_users
ALTER TABLE "read_users" ADD COLUMN "timezone" text;
