-- Migration 0002_number-field-double-precision
-- Generated: 2026-07-17T17:17:25.637Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_inbound_messages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "account_id" text NOT NULL,
  "owner_user_id" text,
  "message_id_header" text NOT NULL,
  "thread_key" text NOT NULL,
  "from" text NOT NULL,
  "to" text,
  "cc" text,
  "subject" text,
  "snippet" text,
  "received_at" timestamp with time zone NOT NULL,
  "body_ref" text,
  "scope" text
);
CREATE INDEX IF NOT EXISTS "read_inbound_messages_tenant_id_idx" ON "read_inbound_messages" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_mail_accounts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "provider" text NOT NULL,
  "auth_method" text NOT NULL,
  "owner_user_id" text,
  "display_name" text,
  "address" text NOT NULL,
  "status" text NOT NULL,
  "watch_state" text,
  "connected_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_mail_accounts_tenant_id_idx" ON "read_mail_accounts" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_mail_seen_messages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "account_id" text NOT NULL,
  "provider_message_id" text NOT NULL,
  "seen_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_mail_seen_messages_tenant_id_idx" ON "read_mail_seen_messages" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_mail_sync_cursors" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "account_id" text NOT NULL,
  "scope" text NOT NULL,
  "cursor" text NOT NULL,
  "updated_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_mail_sync_cursors_tenant_id_idx" ON "read_mail_sync_cursors" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_mail_threads" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "thread_key" text NOT NULL,
  "subject" text,
  "last_message_at" timestamp with time zone NOT NULL,
  "message_count" integer NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_mail_threads_tenant_id_idx" ON "read_mail_threads" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_user_mfa" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "totp_secret" text NOT NULL,
  "recovery_codes" text NOT NULL,
  "enabled_at" timestamp with time zone NOT NULL,
  "last_used_at" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "read_user_mfa_tenant_id_idx" ON "read_user_mfa" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_user_mfa_user_unique" ON "read_user_mfa" ("user_id", "tenant_id");

-- === Changed tables ===
-- file_refs
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
DROP TABLE IF EXISTS "file_refs";
CREATE TABLE IF NOT EXISTS "file_refs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "deleted_at" timestamp with time zone,
  "deleted_by_id" text,
  "storage_key" text NOT NULL,
  "file_name" text NOT NULL,
  "mime_type" text NOT NULL,
  "size" double precision NOT NULL,
  "entity_type" text,
  "entity_id" text,
  "field_name" text
);
CREATE INDEX IF NOT EXISTS "file_refs_tenant_id_idx" ON "file_refs" ("tenant_id");

-- read_cap_counters
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
DROP TABLE IF EXISTS "read_cap_counters";
CREATE TABLE IF NOT EXISTS "read_cap_counters" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "cap_name" text NOT NULL,
  "value" double precision DEFAULT 0 NOT NULL,
  "period_start" timestamp with time zone NOT NULL,
  "last_soft_warned_at" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "read_cap_counters_tenant_id_idx" ON "read_cap_counters" ("tenant_id");

-- read_job_runs
-- WARN: column-type-change integer → double precision. Review USING-clause if needed.
ALTER TABLE "read_job_runs" ALTER COLUMN "duration" TYPE double precision;
