-- Migration 0003_integer-bigint-cap-jobs-file-fields
-- Generated: 2026-07-19T15:33:32.831Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- file_refs
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
-- WARN: destructive change (column type change: size) forces DROP+CREATE + full event replay.
-- Consider an Expand/Contract split across two releases to avoid the rebuild — see docs/guides/expand-contract-managed-projections.md.
DROP TABLE IF EXISTS "file_refs";
CREATE TABLE IF NOT EXISTS "file_refs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "deleted_at" timestamp with time zone,
  "deleted_by_id" text,
  "storage_key" text NOT NULL,
  "file_name" text NOT NULL,
  "mime_type" text NOT NULL,
  "size" bigint NOT NULL,
  "entity_type" text,
  "entity_id" text,
  "field_name" text
);
CREATE INDEX IF NOT EXISTS "file_refs_tenant_id_idx" ON "file_refs" ("tenant_id");

-- read_cap_counters
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
-- WARN: destructive change (column type change: value) forces DROP+CREATE + full event replay.
-- Consider an Expand/Contract split across two releases to avoid the rebuild — see docs/guides/expand-contract-managed-projections.md.
DROP TABLE IF EXISTS "read_cap_counters";
CREATE TABLE IF NOT EXISTS "read_cap_counters" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "cap_name" text NOT NULL,
  "value" bigint DEFAULT 0 NOT NULL,
  "period_start" timestamp with time zone NOT NULL,
  "last_soft_warned_at" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "read_cap_counters_tenant_id_idx" ON "read_cap_counters" ("tenant_id");

-- read_job_runs
-- WARN: column-type-change double precision → integer. Review USING-clause if needed.
ALTER TABLE "read_job_runs" ALTER COLUMN "duration" TYPE integer;
