-- Migration 0003_notes-history
-- Generated: 2026-08-01T16:21:46.882Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_note_entries" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "entity_type" text NOT NULL,
  "entity_id" text NOT NULL,
  "author_id" text,
  "body" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_note_entries_tenant_id_idx" ON "read_note_entries" ("tenant_id");
