-- Migration 0004_content-foundation-merge
-- Generated: 2026-08-01T21:42:01.065Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_template_resources
ALTER TABLE "read_template_resources" ADD COLUMN "title" text;
ALTER TABLE "read_template_resources" ADD COLUMN "folder" text;

-- === Dropped tables ===
-- DESTRUCTIVE: DROP TABLE IF EXISTS "read_text_blocks";  -- uncomment + ensure backup + run during maintenance window
