-- Migration 0005_user-content-entries
-- Generated: 2026-08-02T16:02:10.870Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_user_content_entries" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "owner_id" text NOT NULL,
  "slug" text NOT NULL,
  "kind" text NOT NULL,
  "locale" text NOT NULL,
  "title" text,
  "folder" text,
  "content" text,
  "content_format" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_user_content_entries_tenant_id_idx" ON "read_user_content_entries" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_user_content_entries_unique" ON "read_user_content_entries" ("tenant_id", "owner_id", "slug", "kind", "locale");
