-- Migration 0006_embedded-list-lines
-- Generated: 2026-08-02T20:10:18.936Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_ledger_transactions
ALTER TABLE "read_ledger_transactions" ALTER COLUMN "lines" SET DEFAULT '[]'::jsonb;
