-- Migration 0007_form-draft
-- Generated: 2026-08-10T13:31:47.332Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_form_drafts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "owner_id" text,
  "draft_key" text NOT NULL,
  "draft" jsonb DEFAULT '{}'::jsonb NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_form_drafts_tenant_id_idx" ON "read_form_drafts" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_form_drafts_tenant_owner_key_uniq" ON "read_form_drafts" ("tenant_id", "owner_id", "draft_key");
