-- Migration 0008_ledger-date-column-1924
-- Generated: 2026-08-11T10:36:25.721Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_ledger_schedules
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
-- WARN: destructive change (column type change: start_date, end_date) forces DROP+CREATE + full event replay.
-- Consider an Expand/Contract split across two releases to avoid the rebuild — see docs/guides/expand-contract-managed-projections.md.
DROP TABLE IF EXISTS "read_ledger_schedules";
CREATE TABLE IF NOT EXISTS "read_ledger_schedules" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "description" text NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date,
  "interval" text NOT NULL,
  "amount" integer NOT NULL,
  "debit_account_id" text NOT NULL,
  "credit_account_id" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_ledger_schedules_tenant_id_idx" ON "read_ledger_schedules" ("tenant_id");

-- read_ledger_transactions
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
-- WARN: destructive change (column type change: date) forces DROP+CREATE + full event replay.
-- Consider an Expand/Contract split across two releases to avoid the rebuild — see docs/guides/expand-contract-managed-projections.md.
DROP TABLE IF EXISTS "read_ledger_transactions";
CREATE TABLE IF NOT EXISTS "read_ledger_transactions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "date" date NOT NULL,
  "description" text NOT NULL,
  "reference" text,
  "status" text NOT NULL,
  "lines" jsonb DEFAULT '[]'::jsonb NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_ledger_transactions_tenant_id_idx" ON "read_ledger_transactions" ("tenant_id");
