-- Migration 0009_form-draft-owner-required
-- Generated: 2026-08-12T11:39:14.101Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_form_drafts
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
-- WARN: destructive change (column(s) set NOT NULL: owner_id) forces DROP+CREATE + full event replay.
-- Consider an Expand/Contract split across two releases to avoid the rebuild — see docs/guides/expand-contract-managed-projections.md.
DROP TABLE IF EXISTS "read_form_drafts";
CREATE TABLE IF NOT EXISTS "read_form_drafts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "owner_id" text NOT NULL,
  "draft_key" text NOT NULL,
  "draft" jsonb DEFAULT '{}'::jsonb NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_form_drafts_tenant_id_idx" ON "read_form_drafts" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_form_drafts_tenant_owner_key_uniq" ON "read_form_drafts" ("tenant_id", "owner_id", "draft_key");
