-- Migration 0013_session-last-seen-at
-- Generated: 2026-08-19T11:48:10.995Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- store_user_sessions
ALTER TABLE "store_user_sessions" ADD COLUMN "last_seen_at" timestamptz;
