-- Migration 0015_pii-field-api-v2-bidx
-- Generated: 2026-08-19T18:36:18.563Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_users
ALTER TABLE "read_users" ADD COLUMN "display_name_bidx" text;
CREATE INDEX IF NOT EXISTS "read_users_display_name_bidx_idx" ON "read_users" ("display_name_bidx");
