-- Migration 0016_note-entry-author-name
-- Generated: 2026-08-21T14:33:42.199Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_note_entries
ALTER TABLE "read_note_entries" ADD COLUMN "author_name" text;
