-- Migration 0019_workflow-run-pending
-- Generated: 2026-09-04T08:26:03.460Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "workflow_run_pending" (
  "run_id" uuid NOT NULL,
  "tenant_id" uuid NOT NULL,
  "workflow_name" text NOT NULL,
  "step_index" integer NOT NULL,
  "suspension_event_type" text NOT NULL,
  "wake_at" timestamp with time zone NOT NULL,
  "retry_attempt" integer,
  "definition_fingerprint" text,
  "wait_event_type" text,
  "match_expr" jsonb,
  "trigger_event_type" text,
  "trigger_payload" jsonb,
  CONSTRAINT "workflow_run_pending_pkey" PRIMARY KEY("tenant_id","run_id","step_index")
);
CREATE INDEX IF NOT EXISTS "workflow_run_pending_tenant_wake_at_idx" ON "workflow_run_pending" ("tenant_id", "wake_at");
CREATE INDEX IF NOT EXISTS "workflow_run_pending_wait_event_type_idx" ON "workflow_run_pending" ("wait_event_type");
