-- Migration 0020_channel-in-app-table
-- Generated: 2026-09-10T07:22:56.373Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "in_app_messages" (
  "id" serial PRIMARY KEY,
  "tenant_id" uuid NOT NULL,
  "user_id" text NOT NULL,
  "notification_type" text NOT NULL,
  "title" text NOT NULL,
  "body" text,
  "data" text,
  "is_read" boolean DEFAULT false NOT NULL,
  "read_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
