-- Migration 0022_add-payments-table
-- Generated: 2026-09-11T13:49:19.956Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_payments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "provider_name" text NOT NULL,
  "provider_customer_id" text NOT NULL,
  "price_id" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_payments_tenant_id_idx" ON "read_payments" ("tenant_id");
