-- Migration 0024_add-ledger-subject-columns
-- Generated: 2026-09-12T06:54:41.905Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_ledger_schedules
ALTER TABLE "read_ledger_schedules" ADD COLUMN "subject_type" text;
ALTER TABLE "read_ledger_schedules" ADD COLUMN "subject_id" text;
CREATE INDEX IF NOT EXISTS "read_ledger_schedules_tenant_id_subject_type_subject_id_idx" ON "read_ledger_schedules" ("tenant_id", "subject_type", "subject_id");

-- read_ledger_transactions
ALTER TABLE "read_ledger_transactions" ADD COLUMN "subject_type" text;
ALTER TABLE "read_ledger_transactions" ADD COLUMN "subject_id" text;
CREATE INDEX IF NOT EXISTS "read_ledger_transactions_tenant_id_subject_type_subject_id_idx" ON "read_ledger_transactions" ("tenant_id", "subject_type", "subject_id");
