-- Migration 0026_add-notification-address-opt-out
-- Generated: 2026-09-25T14:52:44.007Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_notification_address_opt_outs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "address_hash" text NOT NULL,
  "notification_type" text NOT NULL,
  "channel" text NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "read_notification_address_opt_outs_unique" ON "read_notification_address_opt_outs" ("tenant_id", "address_hash", "notification_type", "channel");
