-- Migration 0027_add-subscription-cancel-at
-- Generated: 2026-09-27T00:50:48.724Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_subscriptions
ALTER TABLE "read_subscriptions" ADD COLUMN "cancel_at" timestamptz;
