-- Migration 0028_add-ledger-account-code-unique-index
-- Generated: 2026-09-27T09:19:30.544Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_ledger_accounts
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
-- WARN: destructive change (new UNIQUE index(es): read_ledger_accounts_tenant_id_code_uidx) forces DROP+CREATE + full event replay.
-- Consider an Expand/Contract split across two releases to avoid the rebuild — see docs/guides/expand-contract-managed-projections.md.
DROP TABLE IF EXISTS "read_ledger_accounts";
CREATE TABLE IF NOT EXISTS "read_ledger_accounts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "name" text NOT NULL,
  "type" text NOT NULL,
  "code" text,
  "parent_id" text
);
CREATE INDEX IF NOT EXISTS "read_ledger_accounts_tenant_id_idx" ON "read_ledger_accounts" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_ledger_accounts_tenant_id_code_uidx" ON "read_ledger_accounts" ("tenant_id", "code") WHERE "code" IS NOT NULL;
