-- Migration 0029_add-metrics-indexes
-- Generated: 2026-10-01T06:43:30.088Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- store_delivery_attempts
CREATE INDEX IF NOT EXISTS "store_delivery_attempts_tenant_id_created_at_idx" ON "store_delivery_attempts" ("tenant_id", "created_at");

-- store_job_runs
CREATE INDEX IF NOT EXISTS "store_job_runs_started_at_idx" ON "store_job_runs" ("started_at");

-- store_user_sessions
CREATE INDEX IF NOT EXISTS "store_user_sessions_tenant_id_last_seen_at_idx" ON "store_user_sessions" ("tenant_id", "last_seen_at");
