-- Migration 0030_add-ledger-schedule-source-ref
-- Generated: 2026-10-01T15:00:56.448Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_ledger_schedules
ALTER TABLE "read_ledger_schedules" ADD COLUMN "source_ref" text;
CREATE INDEX IF NOT EXISTS "read_ledger_schedules_tenant_id_source_ref_idx" ON "read_ledger_schedules" ("tenant_id", "source_ref");
