-- Migration 0031_workflow-pending-trigger-event-ref
-- Generated: 2026-10-03T11:19:50.244Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- workflow_run_pending
ALTER TABLE "workflow_run_pending" ADD COLUMN "trigger_event_ref" jsonb;
