-- Migration 0032_add-invitation-global-roles
-- Generated: 2026-10-03T16:50:21.684Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_tenant_invitations
ALTER TABLE "read_tenant_invitations" ADD COLUMN "global_roles" jsonb DEFAULT '[]'::jsonb NOT NULL;
