-- Migration 0033_waitlist
-- Generated: 2026-10-03T17:22:11.770Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_waitlist_entries" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "name" text NOT NULL,
  "name_bidx" text,
  "email" text NOT NULL,
  "email_bidx" text,
  "company" text,
  "portfolio" text,
  "message" text,
  "locale" text NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "submitted_at" timestamp with time zone NOT NULL,
  "invited_at" timestamp with time zone,
  "invited_by" text,
  "linked_tenant_id" text
);
CREATE INDEX IF NOT EXISTS "read_waitlist_entries_tenant_id_idx" ON "read_waitlist_entries" ("tenant_id");
CREATE INDEX IF NOT EXISTS "read_waitlist_entries_name_bidx_idx" ON "read_waitlist_entries" ("name_bidx");
CREATE INDEX IF NOT EXISTS "read_waitlist_entries_email_bidx_idx" ON "read_waitlist_entries" ("email_bidx");
