-- Migration 0034_drop-retired-read-job-runs
-- Generated: 2026-10-03T21:55:22.716Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Retired framework tables ===
-- read_job_runs: retired since framework 0.210.0 — replaced by store_job_runs; the job run history was not migrated (operational data, not a system of record)
DROP TABLE IF EXISTS "read_job_runs";
