-- Migration 0035_add-delivery-attempt-confirmed
-- Generated: 2026-10-04T06:14:37.501Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- store_delivery_attempts
ALTER TABLE "store_delivery_attempts" ADD COLUMN "confirmed" boolean;
