-- Migration 0036_add-cap-reservations
-- Generated: 2026-10-05T09:30:44.448Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "store_cap_reservations" (
  "id" uuid PRIMARY KEY,
  "tenant_id" uuid NOT NULL,
  "cap_name" text NOT NULL,
  "kind" text NOT NULL,
  "period_start_iso" text,
  "amount" integer NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "created_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "store_cap_reservations_tenant_id_cap_name_expires_at_idx" ON "store_cap_reservations" ("tenant_id", "cap_name", "expires_at");
