-- Migration 0037_add-in-app-messages-index
-- Generated: 2026-10-08T11:58:56.133Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- in_app_messages
CREATE INDEX IF NOT EXISTS "in_app_messages_tenant_user_created_idx" ON "in_app_messages" ("tenant_id", "user_id", "created_at");
