-- Migration 0038_add-index-notes-mentions-and-job-failures
-- Generated: 2026-10-08T12:29:01.623Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_note_mentions
CREATE INDEX IF NOT EXISTS "read_note_mentions_tenant_id_subject_id_idx" ON "read_note_mentions" ("tenant_id", "subject_id");

-- store_tenant_job_failures
CREATE INDEX IF NOT EXISTS "store_tenant_job_failures_tenant_job_subject_idx" ON "store_tenant_job_failures" ("tenant_id", "job_name", "subject");
CREATE INDEX IF NOT EXISTS "store_tenant_job_failures_tenant_failed_at_idx" ON "store_tenant_job_failures" ("tenant_id", "failed_at");
CREATE INDEX IF NOT EXISTS "store_tenant_job_failures_failed_at_idx" ON "store_tenant_job_failures" ("failed_at");
