-- Migration 0039_add-index-note-entries-tenant-entity
-- Generated: 2026-10-08T18:22:41.908Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_note_entries
CREATE INDEX IF NOT EXISTS "read_note_entries_tenant_id_entity_type_entity_id_idx" ON "read_note_entries" ("tenant_id", "entity_type", "entity_id");
