-- Migration 0040_add-ledger-schedule-source-ref-unique
-- Generated: 2026-10-09T13:53:36.645Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_ledger_schedules
-- In place instead of the generated DROP+CREATE+replay: a rebuild would hit the unique index on historical duplicates.
DROP INDEX IF EXISTS "read_ledger_schedules_tenant_id_source_ref_idx";
CREATE UNIQUE INDEX IF NOT EXISTS "read_ledger_schedules_tenant_id_source_ref_uidx" ON "read_ledger_schedules" ("tenant_id", "source_ref") WHERE "source_ref" IS NOT NULL;
