-- Migration 0042_job-failures-unique
-- Generated: 2026-10-09T14:55:40.298Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- store_tenant_job_failures
-- Concurrent final failures could leave several rows per key; keep the newest before the unique indexes.
DELETE FROM "store_tenant_job_failures" a USING "store_tenant_job_failures" b
  WHERE a."tenant_id" = b."tenant_id" AND a."job_name" = b."job_name"
    AND a."subject" IS NOT DISTINCT FROM b."subject"
    AND (a."failed_at", a."id") < (b."failed_at", b."id");
CREATE UNIQUE INDEX IF NOT EXISTS "store_tenant_job_failures_tenant_job_subject_uidx" ON "store_tenant_job_failures" ("tenant_id", "job_name", "subject") WHERE subject IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "store_tenant_job_failures_tenant_job_null_subject_uidx" ON "store_tenant_job_failures" ("tenant_id", "job_name") WHERE subject IS NULL;
DROP INDEX IF EXISTS "store_tenant_job_failures_tenant_job_subject_idx";
