-- Migration 0043_tenant-job-runs
-- Generated: 2026-10-09T15:50:24.420Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "store_tenant_job_runs" (
  "id" serial PRIMARY KEY,
  "tenant_id" uuid NOT NULL,
  "job_name" text NOT NULL,
  "subject" text,
  "bull_job_id" text NOT NULL,
  "status" text NOT NULL,
  "queued_at" timestamp with time zone,
  "started_at" timestamp with time zone,
  "finished_at" timestamp with time zone,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "store_tenant_job_runs_bull_job_id_unique" ON "store_tenant_job_runs" ("bull_job_id");
CREATE INDEX IF NOT EXISTS "store_tenant_job_runs_tenant_job_subject_idx" ON "store_tenant_job_runs" ("tenant_id", "job_name", "subject");
CREATE INDEX IF NOT EXISTS "store_tenant_job_runs_updated_at_idx" ON "store_tenant_job_runs" ("updated_at");
