// Icon registry: symbolic `IconKey` → lucide-react component. `IconKey` is
// the closed vocabulary a feature author can write (packages/types/src/
// nav-icon.ts); `satisfies` below makes this map a compile-time drift
// guard — a key added to one without the other fails the build.
//
// Runtime data (provider-supplied nav/action icons) is only typed as plain
// `string` at the resolved-tree layer, so an unknown key can still show up
// at runtime on occasion — `Icon` falls back to rendering the raw key as
// text rather than crashing, mirroring the old `ActionGlyph` behavior in
// nav-tree.tsx.
import type { IconKey } from "@cosmicdrift/kumiko-framework/ui-types";
import {
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Building,
  Calculator,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Clock,
  Coins,
  Copy,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  Folder,
  FolderOpen,
  Gauge,
  Hash,
  Home,
  Info,
  KeyRound,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  Link,
  List,
  Loader2,
  Lock,
  Mail,
  MapPin,
  MoreHorizontal,
  MoreVertical,
  Package,
  Palette,
  Pencil,
  Phone,
  PiggyBank,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Table,
  Tag,
  Trash2,
  TrendingUp,
  Undo2,
  Upload,
  User,
  Users,
  Wallet,
  Wand2,
  X,
  XCircle,
} from "lucide-react";
import type { ReactNode } from "react";
import { cn } from "../lib/cn";

export const ICONS = {
  dashboard: LayoutDashboard,
  "layout-grid": LayoutGrid,
  "book-open": BookOpen,
  "clipboard-list": ClipboardList,
  package: Package,
  gauge: Gauge,
  list: List,
  table: Table,
  layers: Layers,
  building: Building,
  calculator: Calculator,
  wallet: Wallet,
  coins: Coins,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  chart: LineChart,
  "bar-chart": BarChart3,
  trending: TrendingUp,
  sparkles: Sparkles,
  wand: Wand2,
  calendar: CalendarDays,
  file: FileText,
  folder: Folder,
  "folder-open": FolderOpen,
  home: Home,
  bell: Bell,
  shield: Shield,
  "shield-check": ShieldCheck,
  send: Send,
  settings: Settings,
  users: Users,
  user: User,
  search: Search,
  tag: Tag,
  key: KeyRound,
  link: Link,
  palette: Palette,
  share: Share2,
  server: Server,
  mail: Mail,
  lock: Lock,
  hash: Hash,
  download: Download,
  upload: Upload,
  rocket: Rocket,
  plus: Plus,
  languages: Languages,
  pencil: Pencil,
  trash: Trash2,
  check: Check,
  x: X,
  copy: Copy,
  eye: Eye,
  "eye-off": EyeOff,
  filter: Filter,
  refresh: RefreshCw,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  "external-link": ExternalLink,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  save: Save,
  undo: Undo2,
  archive: Archive,
  star: Star,
  flag: Flag,
  clock: Clock,
  "map-pin": MapPin,
  phone: Phone,
  printer: Printer,
  "alert-triangle": AlertTriangle,
  info: Info,
  "check-circle": CheckCircle2,
  "x-circle": XCircle,
  loader: Loader2,
} as const satisfies Readonly<Record<IconKey, typeof Folder>>;

// Widened alias for runtime lookups against the plain `string` icon keys
// resolved-tree nodes carry — not the closed IconKey union ICONS itself is
// typed against.
const ICON_LOOKUP: Readonly<Record<string, typeof Folder | undefined>> = ICONS;

export function Icon({
  name,
  className,
}: {
  readonly name: IconKey;
  readonly className?: string;
}): ReactNode {
  const LucideIcon = Object.hasOwn(ICONS, name) ? ICON_LOOKUP[name] : undefined;
  if (LucideIcon !== undefined) return <LucideIcon aria-hidden="true" className={className} />;
  return (
    <span aria-hidden="true" className={cn("text-xs", className)}>
      {name}
    </span>
  );
}
