approvedGitRepositories:
  - "**"

checksumBehavior: throw

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  cosmicdriftgamestudio:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${GITHUB_TOKEN:-}"
