import type { FeatureDefinition } from "../engine/types";
import { buildDrizzleTable, toTableName } from "./table-builder";

// Column type → drizzle-orm/pg-core import name
const COLUMN_TYPE_MAP: Record<string, string> = {
  PgSerial: "serial",
  PgText: "text",
  PgInteger: "integer",
  PgBoolean: "boolean",
  PgTimestamp: "timestamp",
  PgNumeric: "numeric",
};

/**
 * Generates a Drizzle schema file from feature entity definitions.
 * The output is self-contained TypeScript — only imports from drizzle-orm/pg-core.
 * This allows drizzle-kit to work without any framework dependency.
 *
 * Internally uses buildDrizzleTable to create real Drizzle table objects,
 * then serializes them back to TypeScript source code.
 * This ensures column generation logic exists in only one place (table-builder.ts).
 */
export function generateSchemaSource(features: readonly FeatureDefinition[]): string {
  const lines: string[] = [];
  const usedImports = new Set<string>();

  const tableDefs: string[] = [];

  for (const feature of features) {
    for (const [entityName, entity] of Object.entries(feature.entities)) {
      const table = buildDrizzleTable(entityName, entity);
      const exportName = `${entityName}Table`;
      const tableName = entity.table ?? toTableName(entityName);
      const comment = `// Entity: ${entityName} (feature: ${feature.name})`;

      const { code, imports } = serializeTable(exportName, tableName, table, comment);
      tableDefs.push(code);
      for (const imp of imports) usedImports.add(imp);
    }
  }

  if (tableDefs.length === 0) {
    return "// Auto-generated by kumiko — no entities found\n";
  }

  const sortedImports = [...usedImports].sort();
  lines.push("// Auto-generated by kumiko — DO NOT EDIT");
  lines.push("// Re-run: yarn kumiko migrate generate-schema");
  lines.push("");
  lines.push(`import { ${sortedImports.join(", ")} } from "drizzle-orm/pg-core";`);
  lines.push("");
  lines.push(tableDefs.join("\n\n"));
  lines.push("");

  return lines.join("\n");
}

type SerializedTable = {
  code: string;
  imports: string[];
};

function serializeTable(
  exportName: string,
  tableName: string,
  // biome-ignore lint/suspicious/noExplicitAny: Drizzle table entries are untyped at this abstraction level
  table: any,
  comment: string,
): SerializedTable {
  const imports = new Set<string>(["pgTable"]);
  const columns: string[] = [];

  for (const [key, col] of Object.entries(table) as [string, DrizzleColumn][]) {
    if (!col || typeof col !== "object" || !("columnType" in col)) continue;

    const source = serializeColumn(key, col);
    if (source) {
      columns.push(`  ${source.code}`);
      for (const imp of source.imports) imports.add(imp);
    }
  }

  const code = [
    comment,
    `export const ${exportName} = pgTable("${tableName}", {`,
    columns.join(",\n"),
    `});`,
  ].join("\n");

  return { code, imports: [...imports] };
}

type DrizzleColumn = {
  name: string;
  columnType: string;
  notNull: boolean;
  hasDefault: boolean;
  default: unknown;
  primary: boolean;
  precision?: number;
  scale?: number;
};

type ColumnSource = {
  code: string;
  imports: string[];
};

function serializeColumn(jsKey: string, col: DrizzleColumn): ColumnSource | null {
  const importName = COLUMN_TYPE_MAP[col.columnType];
  if (!importName) return null;

  let code = "";

  // Column constructor with SQL name
  if (col.columnType === "PgNumeric" && col.precision !== undefined) {
    code = `${jsKey}: ${importName}("${col.name}", { precision: ${col.precision}, scale: ${col.scale} })`;
  } else {
    code = `${jsKey}: ${importName}("${col.name}")`;
  }

  // Chained modifiers
  if (col.primary) {
    code += ".primaryKey()";
  }
  if (col.hasDefault && !col.primary) {
    code += serializeDefault(col);
  }
  if (col.notNull && !col.primary) {
    // serial().primaryKey() is implicitly notNull
    code += ".notNull()";
  }

  return { code, imports: [importName] };
}

function serializeDefault(col: DrizzleColumn): string {
  const val = col.default;

  // defaultNow() — Drizzle represents this as a SQL chunk
  if (isDefaultNow(val)) {
    return ".defaultNow()";
  }

  // Literal values
  if (typeof val === "boolean") {
    return `.default(${val})`;
  }
  if (typeof val === "number") {
    return `.default(${val})`;
  }
  if (typeof val === "string") {
    return `.default("${val}")`;
  }

  return "";
}

function isDefaultNow(val: unknown): boolean {
  if (!val || typeof val !== "object") return false;
  // Drizzle's defaultNow() creates a SQL object with queryChunks containing "now()"
  const chunks = (val as { queryChunks?: { value?: string[] }[] }).queryChunks;
  if (!Array.isArray(chunks)) return false;
  return chunks.some((c) => Array.isArray(c.value) && c.value.includes("now()"));
}
