import type { EntityDefinition, FeatureDefinition, FieldDefinition } from "../engine/types";
import { toTableName } from "./table-builder";

/**
 * Generates a Drizzle schema file from feature entity definitions.
 * The output is self-contained TypeScript — only imports from drizzle-orm/pg-core.
 * This allows drizzle-kit to work without any framework dependency.
 */
export function generateSchemaSource(features: readonly FeatureDefinition[]): string {
  const lines: string[] = [];
  const usedImports = new Set<string>();

  // Collect all entity table definitions
  const tableDefs: string[] = [];

  for (const feature of features) {
    for (const [entityName, entity] of Object.entries(feature.entities)) {
      const { code, imports } = generateTableCode(entityName, feature.name, entity);
      tableDefs.push(code);
      for (const imp of imports) usedImports.add(imp);
    }
  }

  if (tableDefs.length === 0) {
    return "// Auto-generated by kumiko — no entities found\n";
  }

  // Build import statement
  const sortedImports = [...usedImports].sort();
  lines.push("// Auto-generated by kumiko — DO NOT EDIT");
  lines.push("// Re-run: yarn kumiko migrate generate-schema");
  lines.push("");
  lines.push(`import { ${sortedImports.join(", ")} } from "drizzle-orm/pg-core";`);
  lines.push("");

  // Add table definitions
  lines.push(tableDefs.join("\n\n"));
  lines.push("");

  return lines.join("\n");
}

type TableCodeResult = {
  code: string;
  imports: string[];
};

function generateTableCode(
  entityName: string,
  featureName: string,
  entity: EntityDefinition,
): TableCodeResult {
  const imports = new Set<string>(["pgTable"]);
  const columns: string[] = [];

  // Base columns
  imports.add("serial");
  imports.add("integer");
  imports.add("timestamp");
  columns.push(`  id: serial("id").primaryKey()`);
  columns.push(`  tenantId: integer("tenant_id").notNull()`);
  columns.push(`  version: integer("version").default(1).notNull()`);
  columns.push(`  insertedAt: timestamp("inserted_at").defaultNow().notNull()`);
  columns.push(`  modifiedAt: timestamp("modified_at")`);
  columns.push(`  insertedById: integer("inserted_by_id")`);
  columns.push(`  modifiedById: integer("modified_by_id")`);

  // Soft delete columns
  if (entity.softDelete) {
    imports.add("boolean");
    columns.push(`  isDeleted: boolean("is_deleted").default(false).notNull()`);
    columns.push(`  deletedAt: timestamp("deleted_at")`);
    columns.push(`  deletedById: integer("deleted_by_id")`);
  }

  // Entity field columns
  for (const [fieldName, field] of Object.entries(entity.fields)) {
    const results = generateFieldColumns(fieldName, field, entity);
    for (const result of results) {
      columns.push(`  ${result.code}`);
      for (const imp of result.imports) imports.add(imp);
    }
  }

  const exportName = `${entityName}Table`;
  const tableName = entity.table ?? toTableName(entityName);

  const code = [
    `// Entity: ${entityName} (feature: ${featureName})`,
    `export const ${exportName} = pgTable("${tableName}", {`,
    columns.join(",\n"),
    `});`,
  ].join("\n");

  return { code, imports: [...imports] };
}

type FieldCodeResult = {
  code: string;
  imports: string[];
};

function generateFieldColumns(
  fieldName: string,
  field: FieldDefinition,
  entity: EntityDefinition,
): FieldCodeResult[] {
  const snakeName = toSnakeCase(fieldName);

  switch (field.type) {
    case "text":
    case "select":
      return [{ code: `${fieldName}: text("${snakeName}")`, imports: ["text"] }];
    case "number":
      return [{ code: `${fieldName}: integer("${snakeName}")`, imports: ["integer"] }];
    case "money": {
      const defaultCurrency = entity.defaultCurrency ?? "EUR";
      return [
        {
          code: `${fieldName}: numeric("${snakeName}", { precision: 19, scale: 4 })`,
          imports: ["numeric"],
        },
        {
          code: `${fieldName}Currency: text("${snakeName}_currency").default("${defaultCurrency}")`,
          imports: ["text"],
        },
      ];
    }
    case "boolean":
      if (field.default !== undefined) {
        return [
          {
            code: `${fieldName}: boolean("${snakeName}").default(${field.default}).notNull()`,
            imports: ["boolean"],
          },
        ];
      }
      return [{ code: `${fieldName}: boolean("${snakeName}")`, imports: ["boolean"] }];
    case "date":
      return [{ code: `${fieldName}: timestamp("${snakeName}")`, imports: ["timestamp"] }];
    case "file":
    case "image":
      return [{ code: `${fieldName}: integer("${snakeName}")`, imports: ["integer"] }];
    case "files":
    case "images":
      return [];
  }
}

function toSnakeCase(str: string): string {
  return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}
