// @runtime client
// Pure string-literal QNs/ids — imported by both server (feature.ts) and
// client (web/client-plugin.tsx). Marked `client`, the most permissive
// category in the kumiko isolation model (runtime may import client, client
// may only import client) — otherwise the runtime isolation guard throws on
// the client imports. Same pattern as text-content/constants.
// Feature name
export const TIER_ENGINE_FEATURE = "tier-engine" as const;

// Qualified write handler names (QN format: scope:type:name).
// Auto-generated by defineEntityCreateHandler / defineEntityUpdateHandler.
export const TierEngineHandlers = {
  create: "tier-engine:write:tier-assignment:create",
  update: "tier-engine:write:tier-assignment:update",
  setTenantTier: "tier-engine:write:set-tenant-tier",
} as const;

// Qualified query handler names.
export const TierEngineQueries = {
  list: "tier-engine:query:tier-assignment:list",
  getActiveTier: "tier-engine:query:get-active-tier",
  getTenantTier: "tier-engine:query:get-tenant-tier",
  tierOptions: "tier-engine:query:tier-options",
} as const;

// Screen-id für den manuellen Tier-Grant-Screen. Apps referenzieren ihn
// qualifiziert in r.nav: `tier-engine:screen:tier-admin`.
export const TIER_ADMIN_SCREEN_ID = "tier-admin" as const;
