// Feature name
export const TIER_ENGINE_FEATURE = "tier-engine" as const;

// Qualified write handler names (QN format: scope:type:name).
// Auto-generated by defineEntityCreateHandler / defineEntityUpdateHandler.
export const TierEngineHandlers = {
  create: "tier-engine:write:tier-assignment:create",
  update: "tier-engine:write:tier-assignment:update",
} as const;

// Qualified query handler names.
export const TierEngineQueries = {
  list: "tier-engine:query:tier-assignment:list",
  getActiveTier: "tier-engine:query:get-active-tier",
} as const;
