// Auto-generated by schema/generate.ts — DO NOT EDIT
// Re-run: bun run schema/generate.ts
// biome-ignore-all format: generated output
// biome-ignore-all assist/source/organizeImports: generated output
// biome-ignore-all lint/style/noNonNullAssertion: generated output — entity-lookup ist immer present per registry-contract

import { buildEntityTable } from "@cosmicdrift/kumiko-framework/db";
import { createConfigFeature } from "@cosmicdrift/kumiko-bundled-features/config";
import { createUserFeature } from "@cosmicdrift/kumiko-bundled-features/user";
import { createTenantFeature } from "@cosmicdrift/kumiko-bundled-features/tenant";
import { createSecretsFeature } from "@cosmicdrift/kumiko-bundled-features/secrets";
import { createAuthMfaFeature } from "@cosmicdrift/kumiko-bundled-features/auth-mfa";
import { createDeliveryFeature } from "@cosmicdrift/kumiko-bundled-features/delivery";
import { createFilesFeature } from "@cosmicdrift/kumiko-bundled-features/files";
import { tierEngineFeature } from "@cosmicdrift/kumiko-bundled-features/tier-engine";
import { capCounterFeature } from "@cosmicdrift/kumiko-bundled-features/cap-counter";
import { createComplianceProfilesFeature } from "@cosmicdrift/kumiko-bundled-features/compliance-profiles";
import { createDataRetentionFeature } from "@cosmicdrift/kumiko-bundled-features/data-retention";
import { createUserDataRightsFeature } from "@cosmicdrift/kumiko-bundled-features/user-data-rights";
import { createTextContentFeature } from "@cosmicdrift/kumiko-bundled-features/text-content";
import { createTemplateResolverFeature } from "@cosmicdrift/kumiko-bundled-features/template-resolver";
import { createManagedPagesFeature } from "@cosmicdrift/kumiko-bundled-features/managed-pages";
import { customFieldsFeature } from "@cosmicdrift/kumiko-bundled-features/custom-fields";
import { tagsFeature } from "@cosmicdrift/kumiko-bundled-features/tags";
import { foldersFeature } from "@cosmicdrift/kumiko-bundled-features/folders";
import { ledgerFeature } from "@cosmicdrift/kumiko-bundled-features/ledger";

const _config = createConfigFeature();
const _user = createUserFeature();
const _tenant = createTenantFeature();
const _secrets = createSecretsFeature();
const _authMfa = createAuthMfaFeature({ setupTokenSecret: "stub-setup-secret-at-least-32-bytes-long!!", challengeTokenSecret: "stub-challenge-secret-at-least-32-bytes!!", issuer: "stub" });
const _delivery = createDeliveryFeature();
const _files = createFilesFeature();
const _tierEngine = tierEngineFeature;
const _capCounter = capCounterFeature;
const _complianceProfiles = createComplianceProfilesFeature();
const _dataRetention = createDataRetentionFeature();
const _userDataRights = createUserDataRightsFeature();
const _textContent = createTextContentFeature();
const _templateResolver = createTemplateResolverFeature();
const _managedPages = createManagedPagesFeature({ resolveApexTenant: () => null, allowCustomCss: true });
const _customFields = customFieldsFeature;
const _tags = tagsFeature;
const _folders = foldersFeature;
const _ledger = ledgerFeature;

export const configValueTable = buildEntityTable("config-value", _config.entities["config-value"]!);
export const userTable = buildEntityTable("user", _user.entities["user"]!);
export const tenantTable = buildEntityTable("tenant", _tenant.entities["tenant"]!);
export const tenantMembershipTable = buildEntityTable("tenant-membership", _tenant.entities["tenant-membership"]!);
export const tenantInvitationTable = buildEntityTable("tenant-invitation", _tenant.entities["tenant-invitation"]!);
export const tenantSecretTable = buildEntityTable("tenant-secret", _secrets.entities["tenant-secret"]!);
export const userMfaTable = buildEntityTable("user-mfa", _authMfa.entities["user-mfa"]!);
export const notificationPreferenceTable = buildEntityTable("notification-preference", _delivery.entities["notification-preference"]!);
export const fileRefTable = buildEntityTable("fileRef", _files.entities["fileRef"]!);
export const tierAssignmentTable = buildEntityTable("tier-assignment", _tierEngine.entities["tier-assignment"]!);
export const capCounterTable = buildEntityTable("cap-counter", _capCounter.entities["cap-counter"]!);
export const tenantComplianceProfileTable = buildEntityTable("tenant-compliance-profile", _complianceProfiles.entities["tenant-compliance-profile"]!);
export const tenantRetentionOverrideTable = buildEntityTable("tenant-retention-override", _dataRetention.entities["tenant-retention-override"]!);
export const exportJobTable = buildEntityTable("export-job", _userDataRights.entities["export-job"]!);
export const exportDownloadTokenTable = buildEntityTable("export-download-token", _userDataRights.entities["export-download-token"]!);
export const downloadAttemptTable = buildEntityTable("download-attempt", _userDataRights.entities["download-attempt"]!);
export const textBlockTable = buildEntityTable("text-block", _textContent.entities["text-block"]!);
export const templateResourceTable = buildEntityTable("template-resource", _templateResolver.entities["template-resource"]!);
export const pageTable = buildEntityTable("page", _managedPages.entities["page"]!);
export const fieldDefinitionTable = buildEntityTable("field-definition", _customFields.entities["field-definition"]!);
export const tagTable = buildEntityTable("tag", _tags.entities["tag"]!);
export const tagAssignmentTable = buildEntityTable("tag-assignment", _tags.entities["tag-assignment"]!);
export const folderTable = buildEntityTable("folder", _folders.entities["folder"]!);
export const folderAssignmentTable = buildEntityTable("folder-assignment", _folders.entities["folder-assignment"]!);
export const accountTable = buildEntityTable("account", _ledger.entities["account"]!);
export const transactionTable = buildEntityTable("transaction", _ledger.entities["transaction"]!);
export const scheduleTable = buildEntityTable("schedule", _ledger.entities["schedule"]!);
export { deliveryAttemptsTable } from "@cosmicdrift/kumiko-bundled-features/delivery";
export { mailAccountsProjectionTable, inboundMessagesProjectionTable, mailThreadsProjectionTable } from "@cosmicdrift/kumiko-bundled-features/inbound-mail-foundation";
export { subscriptionsProjectionTable } from "@cosmicdrift/kumiko-bundled-features/billing-foundation";
export { globalFeatureStateTable } from "@cosmicdrift/kumiko-bundled-features/feature-toggles";
export { jobRunsTable, jobRunLogsTable } from "@cosmicdrift/kumiko-bundled-features/jobs";
