import { buildDrizzleTable } from "@cosmicdrift/kumiko-framework/db";
import {
  access,
  createEntity,
  createTextField,
  createTimestampField,
} from "@cosmicdrift/kumiko-framework/engine";

// userSession — one row per signed-in client (browser tab, mobile app).
// The PRIMARY key is the sid — generated by the framework at login time and
// embedded in the JWT's `jti` claim. Using sid-as-PK means the auth middleware
// can look a session up with a single point-read instead of a (userId, sid)
// lookup, which matters because the check runs on every authenticated request.
//
// Fields that are system-managed (userId, revokedAt, expiresAt, etc.) are
// write-locked to the privileged role so the feature's handlers can still
// mutate them via ctx.db inside a transaction, but no user request can bypass
// the revocation flow by poking the column directly.
export const userSessionEntity = createEntity({
  // Entity-Key ist "user-session" (mit Dash), toTableName's snake-case-
  // Transform käme auf "read_user-sessions" → kein valides SQL ohne Quoting.
  // Deshalb expliziter Override auf den read_-konformen Namen.
  table: "read_user_sessions",
  // sid-as-PK: the sessionCreator callback generates the UUID, returns it to
  // the framework; the framework stamps it as `jti`; here the same value is
  // the row primary key. Single source of truth for the identifier.
  // No softDelete: revocation is its own lifecycle (revokedAt timestamp), not
  // a delete — we want to keep the audit trail of revoked sessions for the
  // "your devices" UI ("signed out 3 days ago").
  softDelete: false,
  fields: {
    userId: createTextField({
      required: true,
      maxLength: 36,
      access: { write: access.privileged },
    }),
    tenantId: createTextField({
      required: true,
      maxLength: 36,
      access: { write: access.privileged },
    }),
    createdAt: createTimestampField({
      required: true,
      access: { write: access.privileged },
    }),
    expiresAt: createTimestampField({
      required: true,
      access: { write: access.privileged },
    }),
    // Set when the session is revoked (logout, switch-tenant, password-change,
    // admin action). Middleware treats `revokedAt != null` as "blocked" and
    // returns 401; the row sticks around for the audit trail.
    revokedAt: createTimestampField({
      access: { write: access.privileged },
    }),
    ip: createTextField({
      maxLength: 64,
      access: { write: access.privileged },
    }),
    userAgent: createTextField({
      maxLength: 512,
      access: { write: access.privileged },
    }),
  },
});

export const userSessionTable = buildDrizzleTable("user_session", userSessionEntity);
