// Barrel: re-exports all types from logical modules
// Duplicate types (OnDeleteStrategy, ConfigScope, ConcurrencyMode, LifecycleHookType)
// are defined ONLY in constants.ts — re-exported here for backwards compatibility.

// Re-export types that were duplicated in types.ts but are canonical in constants.ts
export type {
  ConcurrencyMode,
  ConfigScope,
  LifecycleHookType,
  OnDeleteStrategy,
} from "../constants";
export type {
  ConfigAccessor,
  ConfigAccessorFactory,
  ConfigBounds,
  ConfigComputedContext,
  ConfigComputedFn,
  ConfigDefinition,
  ConfigKeyAccess,
  ConfigKeyDefinition,
  ConfigKeyHandle,
  ConfigKeyType,
  ConfigResolver,
  ConfigStoredRow,
  ConfigValue,
  ConfigValueSource,
  ConfigValueWithSource,
  JobDefinition,
  JobHandlerFn,
  JobRunIn,
  JobTrigger,
  NotificationDataFn,
  NotificationDefinition,
  NotificationRecipientFn,
  NotificationTemplateFn,
  ReferenceDataDef,
  RegistrarExtensionDef,
  RegistrarExtensionHooks,
  RegistrarExtensionRegistration,
  RunIn,
  TranslationEntry,
  TranslationKeys,
  TranslationsDef,
  UiExtensionDef,
} from "./config";
export type {
  FeatureDefinition,
  FeatureMetricDef,
  FeatureMetricType,
  FeatureRegistrar,
  MetricOptions,
  Registry,
  SecretKeyDefinition,
  SecretKeyHandle,
  SecretOptions,
} from "./feature";
export type {
  AnyFileFieldDef,
  BooleanFieldDef,
  DateFieldDef,
  DefaultCurrency,
  EmbeddedFieldDef,
  EmbeddedSubFieldDef,
  EntityDefinition,
  FieldAccess,
  FieldDefinition,
  FileFieldDef,
  FilesFieldDef,
  ImageFieldDef,
  ImagesFieldDef,
  LocatedTimestampFieldDef,
  MoneyFieldDef,
  NumberFieldDef,
  SelectFieldDef,
  TextFieldDef,
  TimestampFieldDef,
  TransitionMap,
  TzFieldDef,
} from "./fields";
export { DEFAULT_CURRENCIES, isFileField } from "./fields";
export type {
  AccessRule,
  AggregateStreamHandle,
  AppContext,
  AppendEventArgs,
  AuthClaimsContext,
  AuthClaimsFn,
  AuthClaimsHookDef,
  ClaimKeyDefinition,
  ClaimKeyHandle,
  ClaimKeyJsType,
  ClaimKeyType,
  EntityRef,
  EventDef,
  EventMigrationDef,
  EventUpcastCtx,
  EventUpcastFn,
  FetchForWritingArgs,
  HandlerContext,
  HandlerRef,
  JobContext,
  JobRunnerRef,
  NameOrRef,
  NotifyFactory,
  NotifyFn,
  NotifyOptions,
  NotifyPriority,
  QueryEvent,
  QueryHandlerDef,
  QueryHandlerFn,
  RateLimitOption,
  RateLimitPer,
  SessionUser,
  WriteEvent,
  WriteHandlerDef,
  WriteHandlerFn,
  WriteResult,
} from "./handlers";
export { resolveName } from "./handlers";
export type {
  DeleteContext,
  EntityHookMap,
  HookMap,
  HookOwner,
  HookPhase,
  LifecycleHookFn,
  LifecycleResult,
  OwnedFn,
  PhasedHook,
  PostDeleteBatchHookFn,
  PostDeleteHookFn,
  PostSaveBatchHookFn,
  PostSaveHookFn,
  PreDeleteHookFn,
  PreQueryHookFn,
  PreSaveHookFn,
  SaveContext,
  ValidationError,
  ValidationHookFn,
} from "./hooks";
export { HookPhases } from "./hooks";
// Domain-identifier type aliases — see identifiers.ts for rationale.
export type { EntityId, TenantId } from "./identifiers";
export { isSystemTenant, SYSTEM_TENANT_ID } from "./identifiers";
export type { NavDefinition } from "./nav";
export type {
  MspErrorMode,
  MspErrorPolicy,
  MultiStreamApplyFn,
  MultiStreamProjectionDefinition,
  ProjectionDefinition,
  ProjectionTable,
  SingleStreamApplyFn,
} from "./projection";
export type {
  BelongsToRelation,
  EntityRelations,
  HasManyRelation,
  ManyToManyRelation,
  RelationDefinition,
} from "./relations";
export type {
  CustomScreenDefinition,
  CustomScreenRoute,
  EditFieldSpec,
  EditLayout,
  EditSectionSpec,
  EntityEditScreenDefinition,
  EntityListScreenDefinition,
  FieldCondition,
  FieldRenderer,
  ListColumnSpec,
  ScreenComponent,
  ScreenDefinition,
  ScreenSlots,
} from "./screen";
export { normalizeEditField, normalizeListColumn } from "./screen";
