// Barrel: re-exports all types from @cosmicdrift/kumiko-types, plus the
// runtime helpers below that stay framework-side.
// Duplicate types (OnDeleteStrategy, ConfigScope, ConcurrencyMode, LifecycleHookType)
// are defined ONLY in constants.ts — re-exported here for backwards compatibility.

export type {
  ConfigAccessor,
  ConfigAccessorFactory,
  ConfigBacking,
  ConfigBounds,
  ConfigCascade,
  ConfigCascadeLevel,
  ConfigComputedContext,
  ConfigComputedFn,
  ConfigDefinition,
  ConfigKeyAccess,
  ConfigKeyDefinition,
  ConfigKeyHandle,
  ConfigKeyType,
  ConfigMask,
  ConfigResolver,
  ConfigSecretsReader,
  ConfigSeedDef,
  ConfigStoredRow,
  ConfigStoredRowWithSource,
  ConfigValue,
  ConfigValueSource,
  ConfigValueWithSource,
  CreateSeedOptions,
  CreateTenantSeedOptions,
  CreateUserSeedOptions,
  ExtensionSelectorDef,
  JobDefinition,
  JobHandlerFn,
  JobRunIn,
  JobTrigger,
  NotificationDataFn,
  NotificationDefinition,
  NotificationRecipientFn,
  NotificationTemplateFn,
  ReferenceDataDef,
  RegistrarExtensionDef,
  RegistrarExtensionHooks,
  RegistrarExtensionRegistration,
  RunIn,
  TranslationEntry,
  TranslationKeys,
  TranslationsDef,
  UiExtensionDef,
} from "@cosmicdrift/kumiko-types/config";
export type {
  QueryHandlerDefinition,
  WriteHandlerDefinition,
  WriteHandlerInput,
} from "@cosmicdrift/kumiko-types/define-handler";
export type {
  EntityCrudRegistrar,
  EntityCrudVerb,
  EntityHandlerOptions,
  EntityQueryHandlerOptions,
  RegisterEntityCrudOptions,
} from "@cosmicdrift/kumiko-types/entity-handlers";
// Cross-Feature Compile-Time-Type-Map — features extend per declare-module.
export type {
  KumikoEntityTypeMap,
  KumikoEventTypeMap,
  KumikoHandlerPayloadMap,
  KumikoHandlerResultMap,
} from "@cosmicdrift/kumiko-types/event-type-map";
export type {
  BootCheckContext,
  BootCheckFn,
  FeatureDefinition,
  FeatureMetricDef,
  FeatureMetricType,
  FeatureRegistrar,
  MetricOptions,
  Registry,
  SecretKeyDefinition,
  SecretKeyHandle,
  SecretOptions,
  StoreTableDef,
  StoreTableEntry,
  StoreTableOptions,
  UiHintOption,
  UiHints,
} from "@cosmicdrift/kumiko-types/feature";
export type {
  AnyFileFieldDef,
  BigIntFieldDef,
  BooleanFieldDef,
  ClientDerivedFieldDef,
  DateFieldDef,
  DecimalFieldDef,
  DefaultCurrency,
  DeriveContext,
  DerivedFieldDef,
  DerivedFieldsMap,
  DerivedValueType,
  EmbeddedFieldDef,
  EmbeddedSubFieldDef,
  EntityDefinition,
  EntityIndexDef,
  FieldAccess,
  FieldDefinition,
  FieldsMap,
  FileFieldDef,
  FilesFieldDef,
  ImageFieldDef,
  ImagesFieldDef,
  JsonbFieldDef,
  LocatedTimestampFieldDef,
  LongTextFieldDef,
  MoneyFieldDef,
  MultiSelectFieldDef,
  NumberFieldDef,
  PiiAnnotations,
  ReferenceFieldDef,
  RetentionDef,
  SelectFieldDef,
  TextFieldDef,
  TimestampFieldDef,
  TransitionMap,
  TzFieldDef,
} from "@cosmicdrift/kumiko-types/fields";
export type {
  AccessRule,
  AggregateStreamHandle,
  AppContext,
  AppendEventArgs,
  AppendEventFn,
  AuthClaimsContext,
  AuthClaimsFn,
  AuthClaimsHookDef,
  CamelToKebab,
  ClaimKeyDefinition,
  ClaimKeyHandle,
  ClaimKeyJsType,
  ClaimKeyType,
  DeclarativeEventMigration,
  EntityRef,
  EventDef,
  EventMigrationDef,
  EventPiiFields,
  EventUpcastCtx,
  EventUpcastFn,
  FetchForWritingArgs,
  HandlerContext,
  HandlerRef,
  JobContext,
  JobRunnerRef,
  NameOrRef,
  NotifyFactory,
  NotifyFn,
  NotifyOptions,
  NotifyPriority,
  QualifiedEventName,
  QueryEvent,
  QueryHandlerDef,
  QueryHandlerFn,
  RateLimitOption,
  RateLimitPer,
  SessionUser,
  TryAppendEventFn,
  TryAppendEventResult,
  UnsafeAppendEventFn,
  WriteEvent,
  WriteHandlerDef,
  WriteHandlerFn,
  WriteResult,
} from "@cosmicdrift/kumiko-types/handlers";
export type {
  DeleteContext,
  EntityHookMap,
  HookMap,
  HookOwner,
  HookPhase,
  LifecycleHookFn,
  LifecycleResult,
  OwnedFn,
  PhasedHook,
  PostDeleteBatchHookFn,
  PostDeleteHookFn,
  PostQueryHookFn,
  PostSaveBatchHookFn,
  PostSaveHookFn,
  PreDeleteHookFn,
  PreQueryHookFn,
  PreSaveHookFn,
  SaveContext,
  SearchPayloadContributorFn,
  ValidationError,
  ValidationHookFn,
} from "@cosmicdrift/kumiko-types/hooks";
export type {
  HttpRouteDefinition,
  HttpRouteHandler,
  HttpRouteHandlerDeps,
  HttpRouteMethod,
} from "@cosmicdrift/kumiko-types/http-route";
// Domain-identifier type aliases — see identifiers.ts for rationale.
export type { EntityId, TenantId } from "@cosmicdrift/kumiko-types/identifiers";
export {
  isSystemTenant,
  parseTenantId,
  SYSTEM_TENANT_ID,
} from "@cosmicdrift/kumiko-types/identifiers";
export type { NavDefinition } from "@cosmicdrift/kumiko-types/nav";
export type {
  FromRule,
  FromRuleKind,
  OwnershipClause,
  OwnershipMap,
  OwnershipRef,
  OwnershipRule,
  SqlFragment,
  WhereRule,
  WhereRuleContext,
} from "@cosmicdrift/kumiko-types/ownership";
export type {
  EntityProjectionExtension,
  MspErrorMode,
  MspErrorPolicy,
  MultiStreamApplyFn,
  MultiStreamProjectionDefinition,
  ProjectionDefinition,
  ProjectionTable,
  SingleStreamApplyFn,
} from "@cosmicdrift/kumiko-types/projection";
export type {
  BelongsToRelation,
  EntityRelations,
  HasManyRelation,
  ManyToManyRelation,
  RelationDefinition,
} from "@cosmicdrift/kumiko-types/relations";
export type {
  ActionFormScreenDefinition,
  ConfigEditScreenDefinition,
  CustomScreenDefinition,
  CustomScreenRoute,
  DashboardChartPanel,
  DashboardCustomPanel,
  DashboardFeedPanel,
  DashboardFilterDefinition,
  DashboardListPanel,
  DashboardPanelDefinition,
  DashboardProgressListPanel,
  DashboardScreenDefinition,
  DashboardStatGroupPanel,
  DashboardStatPanel,
  EditExtensionSection,
  EditFieldSpec,
  EditFieldsSection,
  EditLayout,
  EditSectionSpec,
  EntityEditScreenDefinition,
  EntityListScreenDefinition,
  FieldCondition,
  FieldFormatRegistry,
  FieldRenderer,
  FormatSpec,
  ListColumnSpec,
  PlatformComponent,
  ProjectionDetailScreenDefinition,
  ProjectionListScreenDefinition,
  RowAction,
  RowActionNavigate,
  RowActionWriteHandler,
  ScreenDefinition,
  ScreenFilter,
  ScreenFilterOp,
  ScreenSlots,
  ToolbarAction,
} from "@cosmicdrift/kumiko-types/screen";
export type { TargetRef } from "@cosmicdrift/kumiko-types/target-ref";
export type {
  Subscribe,
  TreeAction,
  TreeActionDef,
  TreeActionsHandle,
  TreeChildrenSubscribe,
  TreeNode,
  TreeNodeState,
} from "@cosmicdrift/kumiko-types/tree-node";
export type { WorkspaceDefinition } from "@cosmicdrift/kumiko-types/workspace";
// Re-export types that were duplicated in types.ts but are canonical in constants.ts
export type {
  ConcurrencyMode,
  ConfigScope,
  LifecycleHookType,
  OnDeleteStrategy,
} from "../constants";
export { DEFAULT_CURRENCIES, isFileField } from "../field-helpers";
export { resolveName, withResponseData } from "../handler-helpers";
export { HookPhases } from "../hook-helpers";
export {
  isExtensionEditSection,
  isFormatSpec,
  normalizeEditField,
  normalizeListColumn,
} from "../screen-helpers";
