// Closed vocabulary of icon keys, shared across nav entries, actions,
// metrics and sections. NavDefinition.icon, ScreenNavSugar.icon and
// ConfigMask.icon are all typed against this union, so an unregistered
// key is a compile error at the r.nav()/r.screen()/config-mask call site
// instead of a silent missing-icon at runtime.
//
// The renderer-web ICONS map (packages/renderer-web/src/layout/
// icon-registry.tsx) is checked against this same union via `satisfies`, so
// the two can't drift — add a key here only together with its lucide-react
// entry there, and vice versa.
export type IconKey =
  | "dashboard"
  | "layout-grid"
  | "book-open"
  | "clipboard-list"
  | "package"
  | "gauge"
  | "list"
  | "table"
  | "layers"
  | "building"
  | "calculator"
  | "wallet"
  | "coins"
  | "credit-card"
  | "piggy-bank"
  | "receipt"
  | "chart"
  | "bar-chart"
  | "trending"
  | "sparkles"
  | "wand"
  | "calendar"
  | "file"
  | "folder"
  | "folder-open"
  | "home"
  | "bell"
  | "shield"
  | "shield-check"
  | "send"
  | "settings"
  | "users"
  | "user"
  | "search"
  | "tag"
  | "key"
  | "link"
  | "palette"
  | "share"
  | "server"
  | "mail"
  | "lock"
  | "hash"
  | "download"
  | "upload"
  | "rocket"
  | "plus"
  | "languages"
  | "pencil"
  | "trash"
  | "check"
  | "x"
  | "copy"
  | "eye"
  | "eye-off"
  | "filter"
  | "refresh"
  | "more-horizontal"
  | "more-vertical"
  | "external-link"
  | "arrow-left"
  | "arrow-right"
  | "chevron-down"
  | "chevron-right"
  | "save"
  | "undo"
  | "archive"
  | "star"
  | "flag"
  | "clock"
  | "map-pin"
  | "phone"
  | "printer"
  | "alert-triangle"
  | "info"
  | "check-circle"
  | "x-circle"
  | "loader";

// Deprecated alias — kept so existing imports/call sites of `NavIconKey`
// keep compiling unchanged while the vocabulary grows past the nav-only
// case. New code should use `IconKey`.
export type NavIconKey = IconKey;
