export const TEST_TIMEOUT_MS = {
  unit: 5000,
  integration: 15000,
  dom: 15000,
  // Real providers add network round-trips and provider-side latency the local stack never has.
  real: 120000,
} as const;

export const BUNFIG_FILES = {
  unit: "bunfig.toml",
  integration: "bunfig.integration.toml",
  real: "bunfig.real.toml",
  dom: "bunfig.dom.toml",
} as const;

export type BunfigVariant = "unit" | "integration" | "real";

export type BunfigOptions = {
  readonly dom?: boolean;
  readonly coverage?: boolean;
  readonly install?: { readonly linker: "hoisted" };
};

const PRELOAD_PREFIX = "@cosmicdrift/kumiko-testing/preload";
const DOM_PRELOAD = "./test-setup/dom.preload.ts";

const PRELOADS = {
  unit: [`${PRELOAD_PREFIX}/temporal`, `${PRELOAD_PREFIX}/scrub-env`],
  integration: [`${PRELOAD_PREFIX}/temporal`, `${PRELOAD_PREFIX}/env`],
  real: [`${PRELOAD_PREFIX}/temporal`, `${PRELOAD_PREFIX}/real`],
} as const satisfies Record<BunfigVariant, readonly string[]>;

const ALWAYS_IGNORED = ["**/e2e/**", "**/*.spec.ts", "**/*.spec.tsx", "**/dist/**"] as const;

const COVERAGE_IGNORED = ["**/scripts/**", "**/bin/**"] as const;

function ignoredPaths(variant: BunfigVariant, dom: boolean): readonly string[] {
  switch (variant) {
    case "unit":
      return [
        "**/*.integration.test.ts",
        "**/*.real.test.ts",
        ...(dom ? [] : ["**/*.test.tsx"]),
        ...ALWAYS_IGNORED,
      ];
    case "integration":
      return ["**/*.real.test.ts", ...ALWAYS_IGNORED];
    case "real":
      return ["**/*.integration.test.ts", ...ALWAYS_IGNORED];
  }
}

function tomlStringArray(key: string, items: readonly string[]): string {
  return `${key} = [\n${items.map((item) => `  ${JSON.stringify(item)},`).join("\n")}\n]`;
}

export function renderBunfig(variant: BunfigVariant, opts: BunfigOptions = {}): string {
  const dom = opts.dom === true;
  if (dom && variant !== "unit") {
    throw new Error(`bunfig option "dom" only applies to the unit variant, not "${variant}"`);
  }
  const preload = dom ? [...PRELOADS.unit, DOM_PRELOAD] : PRELOADS[variant];
  const coverageDir = `coverage/${dom ? "dom" : variant}`;

  const lines = [
    `# Generated by kumiko-testing (${dom ? "dom" : variant}) - do not edit, regenerate with \`kumiko-testing bunfig\`.`,
    "# bun ignores a [test] timeout key; the class budget is passed as --timeout by the runner scripts.",
    ...(opts.install !== undefined
      ? ["[install]", `linker = ${JSON.stringify(opts.install.linker)}`, ""]
      : []),
    "[test]",
    tomlStringArray("preload", preload),
    ...(opts.coverage === true
      ? [
          "coverage = true",
          'coverageReporter = ["lcov"]',
          `coverageDir = ${JSON.stringify(coverageDir)}`,
          tomlStringArray("coveragePathIgnorePatterns", COVERAGE_IGNORED),
        ]
      : []),
    tomlStringArray("pathIgnorePatterns", ignoredPaths(variant, dom)),
  ];
  return `${lines.join("\n")}\n`;
}

export function renderBunfigFiles(opts: BunfigOptions = {}): Readonly<Record<string, string>> {
  const { dom, ...shared } = opts;
  return {
    [BUNFIG_FILES.unit]: renderBunfig("unit", shared),
    [BUNFIG_FILES.integration]: renderBunfig("integration", shared),
    [BUNFIG_FILES.real]: renderBunfig("real", shared),
    ...(dom === true ? { [BUNFIG_FILES.dom]: renderBunfig("unit", { ...shared, dom: true }) } : {}),
  };
}
