import { E2E_TIMEOUT_MS } from "./e2e/timeouts";

export const TEST_TIMEOUT_MS = {
  unit: 5000,
  integration: 15000,
  dom: 15000,
  // Same class budget as Playwright real runs (E2E_TIMEOUT_MS.real) — one
  // constant covers both the bun test:real path and defineAppE2eConfig.
  real: E2E_TIMEOUT_MS.real,
} as const;

export const BUNFIG_FILES = {
  unit: "bunfig.toml",
  integration: "bunfig.integration.toml",
  real: "bunfig.real.toml",
  dom: "bunfig.dom.toml",
} as const;

export type BunfigVariant = "unit" | "integration" | "real";

export type BunfigOptions = {
  readonly dom?: boolean;
  readonly coverage?: boolean;
  readonly install?: { readonly linker: "hoisted" };
};

const PRELOAD_PREFIX = "@cosmicdrift/kumiko-testing/preload";
const DOM_PRELOAD = `${PRELOAD_PREFIX}/dom`;

const PRELOADS = {
  unit: [`${PRELOAD_PREFIX}/temporal`, `${PRELOAD_PREFIX}/scrub-env`],
  integration: [`${PRELOAD_PREFIX}/temporal`, `${PRELOAD_PREFIX}/env`],
  real: [`${PRELOAD_PREFIX}/temporal`, `${PRELOAD_PREFIX}/real`],
} as const satisfies Record<BunfigVariant, readonly string[]>;

const ALWAYS_IGNORED = ["**/e2e/**", "**/*.spec.ts", "**/*.spec.tsx", "**/dist/**"] as const;

const COVERAGE_IGNORED = ["**/scripts/**", "**/bin/**"] as const;

function ignoredPaths(variant: BunfigVariant, dom: boolean): readonly string[] {
  switch (variant) {
    case "unit":
      return [
        "**/*.integration.test.ts",
        "**/*.real.test.ts",
        ...(dom ? [] : ["**/*.test.tsx"]),
        ...ALWAYS_IGNORED,
      ];
    case "integration":
      return ["**/*.real.test.ts", ...ALWAYS_IGNORED];
    case "real":
      return ["**/*.integration.test.ts", ...ALWAYS_IGNORED];
  }
}

function tomlStringArray(key: string, items: readonly string[]): string {
  return `${key} = [\n${items.map((item) => `  ${JSON.stringify(item)},`).join("\n")}\n]`;
}

export function renderBunfig(variant: BunfigVariant, opts: BunfigOptions = {}): string {
  const dom = opts.dom === true;
  if (dom && variant !== "unit") {
    throw new Error(`bunfig option "dom" only applies to the unit variant, not "${variant}"`);
  }
  const preload = dom ? [...PRELOADS.unit, DOM_PRELOAD] : PRELOADS[variant];
  const coverageDir = `coverage/${dom ? "dom" : variant}`;

  const lines = [
    `# Generated by kumiko-testing (${dom ? "dom" : variant}) - do not edit, regenerate with \`kumiko-testing bunfig\`.`,
    "# bun ignores a [test] timeout key; the class budget is passed as --timeout by the runner scripts.",
    ...(opts.install !== undefined
      ? ["[install]", `linker = ${JSON.stringify(opts.install.linker)}`, ""]
      : []),
    "[test]",
    tomlStringArray("preload", preload),
    ...(opts.coverage === true
      ? [
          "coverage = true",
          'coverageReporter = ["lcov"]',
          `coverageDir = ${JSON.stringify(coverageDir)}`,
          tomlStringArray("coveragePathIgnorePatterns", COVERAGE_IGNORED),
        ]
      : []),
    tomlStringArray("pathIgnorePatterns", ignoredPaths(variant, dom)),
  ];
  return `${lines.join("\n")}\n`;
}

type BunfigBlock = { readonly header: string; readonly lines: readonly string[] };

// Splits on un-indented `[header]` lines only — real bunfig files never
// indent a table header, and TOML array/inline-table values that happen to
// contain "[" are never alone on their own line. Anything before the first
// header (top-level keys like `preload`/`telemetry`/`smol`/`logLevel`, plus
// the header comments) is its own block under the synthetic header "" —
// dropping it silently lost those keys (kumiko-framework#3120).
function splitBunfigBlocks(content: string): readonly BunfigBlock[] {
  const blocks: { header: string; lines: string[] }[] = [];
  let current: { header: string; lines: string[] } = { header: "", lines: [] };
  for (const line of content.split("\n")) {
    const match = /^\[([^\]]+)\]\s*$/.exec(line);
    if (match?.[1] !== undefined) {
      blocks.push(current);
      current = { header: match[1], lines: [] };
      continue;
    }
    current.lines.push(line);
  }
  blocks.push(current);
  return blocks;
}

function keysIn(lines: readonly string[]): readonly string[] {
  const keys: string[] = [];
  for (const line of lines) {
    const match = /^([A-Za-z_][\w-]*)\s*=/.exec(line.trim());
    if (match?.[1] !== undefined) keys.push(match[1]);
  }
  return keys;
}

export type UnknownBunfigKey = { readonly section: string; readonly key: string };

export type BunfigMergeResult =
  | { readonly ok: true; readonly content: string }
  | { readonly ok: false; readonly unknownKeys: readonly UnknownBunfigKey[] };

// Unlike an unknown key, which blocks the merge, an array entry the template
// stops emitting stays on disk silently until the generator excludes it by
// name, as it does below for the superseded DOM preload path.
const MERGED_ARRAY_KEYS = ["preload", "pathIgnorePatterns", "coveragePathIgnorePatterns"] as const;
type MergedArrayKey = (typeof MERGED_ARRAY_KEYS)[number];

const CURRENT_PACKAGE_PRELOADS = new Set<string>([...Object.values(PRELOADS).flat(), DOM_PRELOAD]);

// Old app-local path of DOM_PRELOAD; excluded so an app that hasn't
// regenerated doesn't run DOM setup twice.
const SUPERSEDED_PRELOADS = new Set<string>(["./test-setup/dom.preload.ts"]);

function isKeepableExtra(key: MergedArrayKey, entry: string): boolean {
  if (key !== "preload") return true;
  if (SUPERSEDED_PRELOADS.has(entry)) return false;
  if (entry.startsWith(PRELOAD_PREFIX)) return CURRENT_PACKAGE_PRELOADS.has(entry);
  return true;
}

function parseTestSection(content: string): Readonly<Record<string, unknown>> {
  const parsed = Bun.TOML.parse(content) as { test?: Record<string, unknown> };
  return parsed.test ?? {};
}

function arrayField(
  testSection: Readonly<Record<string, unknown>>,
  key: MergedArrayKey,
): readonly string[] {
  const value = testSection[key];
  if (typeof value === "string") return [value];
  return Array.isArray(value)
    ? value.filter((item): item is string => typeof item === "string")
    : [];
}

// TOML comments attached to an extra on disk don't survive: only the parsed
// string value is carried over, not the source lines around it.
function appendArrayExtras(
  generated: string,
  key: MergedArrayKey,
  extras: readonly string[],
): string {
  if (extras.length === 0) return generated;
  const extraLines = extras.map((item) => `  ${JSON.stringify(item)},`).join("\n");
  const pattern = new RegExp(`^(${key} = \\[\\n)([\\s\\S]*?)(\\n\\])`, "m");
  return generated.replace(
    pattern,
    (_match, open: string, body: string, close: string) => `${open}${body}\n${extraLines}${close}`,
  );
}

/**
 * Merges freshly generated bunfig content with whatever an app already has
 * on disk. A section this run's `generated` output doesn't touch at all
 * (e.g. `[install]` when `--install` wasn't passed, or `[install.scopes]`
 * for a private-registry token, which renderBunfig never emits) is kept
 * verbatim, appended after the generated content — so a section the
 * template doesn't own this run is never silently dropped. A key inside a
 * section the template DOES emit that isn't in this run's own version of
 * that section (e.g. `concurrency`, `timeout`, kumiko-framework#3120) fails
 * the merge instead of silently disappearing. Within an array key the
 * template does emit on both sides (`preload`, `pathIgnorePatterns`,
 * `coveragePathIgnorePatterns`), entries the app appended on top of the
 * generated ones survive the regeneration instead of being overwritten with
 * the generated array alone.
 */
export function mergeBunfig(generated: string, existingContent: string): BunfigMergeResult {
  const generatedKeysBySection = new Map(
    splitBunfigBlocks(generated).map((block) => [block.header, new Set(keysIn(block.lines))]),
  );
  const blocks = splitBunfigBlocks(existingContent);
  const unknownKeys: UnknownBunfigKey[] = [];
  const foreignBlocks: BunfigBlock[] = [];
  for (const block of blocks) {
    const allowed = generatedKeysBySection.get(block.header);
    if (allowed === undefined) {
      foreignBlocks.push(block);
      continue;
    }
    for (const key of keysIn(block.lines)) {
      if (!allowed.has(key)) unknownKeys.push({ section: block.header, key });
    }
  }
  if (unknownKeys.length > 0) return { ok: false, unknownKeys };
  const generatedTest = parseTestSection(generated);
  const existingTest = parseTestSection(existingContent);
  let content = generated;
  for (const key of MERGED_ARRAY_KEYS) {
    const generatedValues = arrayField(generatedTest, key);
    const existingValues = arrayField(existingTest, key);
    const extras = existingValues.filter(
      (item) => !generatedValues.includes(item) && isKeepableExtra(key, item),
    );
    content = appendArrayExtras(content, key, extras);
  }
  if (foreignBlocks.length === 0) return { ok: true, content };
  const foreignText = foreignBlocks
    .map((block) => `[${block.header}]\n${block.lines.join("\n").replace(/\n+$/, "")}\n`)
    .join("\n");
  return { ok: true, content: `${content}\n${foreignText}` };
}

export function renderBunfigFiles(opts: BunfigOptions = {}): Readonly<Record<string, string>> {
  const { dom, ...shared } = opts;
  return {
    [BUNFIG_FILES.unit]: renderBunfig("unit", shared),
    [BUNFIG_FILES.integration]: renderBunfig("integration", shared),
    [BUNFIG_FILES.real]: renderBunfig("real", shared),
    ...(dom === true ? { [BUNFIG_FILES.dom]: renderBunfig("unit", { ...shared, dom: true }) } : {}),
  };
}
