// Auto-generated by drizzle/generate.ts — DO NOT EDIT
// Re-run: bun run drizzle/generate.ts
// biome-ignore-all format: generated output
// biome-ignore-all assist/source/organizeImports: generated output
// biome-ignore-all lint/style/noNonNullAssertion: generated output — entity-lookup ist immer present per registry-contract

import { buildDrizzleTable } from "@cosmicdrift/kumiko-framework/db";
import { createConfigFeature } from "@cosmicdrift/kumiko-bundled-features/config";
import { createUserFeature } from "@cosmicdrift/kumiko-bundled-features/user";
import { createTenantFeature } from "@cosmicdrift/kumiko-bundled-features/tenant";
import { createSecretsFeature } from "@cosmicdrift/kumiko-bundled-features/secrets";
import { createSessionsFeature } from "@cosmicdrift/kumiko-bundled-features/sessions";
import { createDeliveryFeature } from "@cosmicdrift/kumiko-bundled-features/delivery";
import { createFilesFeature } from "@cosmicdrift/kumiko-bundled-features/files";
import { tierEngineFeature } from "@cosmicdrift/kumiko-bundled-features/tier-engine";
import { capCounterFeature } from "@cosmicdrift/kumiko-bundled-features/cap-counter";
import { createComplianceProfilesFeature } from "@cosmicdrift/kumiko-bundled-features/compliance-profiles";
import { createDataRetentionFeature } from "@cosmicdrift/kumiko-bundled-features/data-retention";
import { createUserDataRightsFeature } from "@cosmicdrift/kumiko-bundled-features/user-data-rights";
import { createTextContentFeature } from "@cosmicdrift/kumiko-bundled-features/text-content";
import { createTemplateResolverFeature } from "@cosmicdrift/kumiko-bundled-features/template-resolver";
import { customFieldsFeature } from "@cosmicdrift/kumiko-bundled-features/custom-fields";

const _config = createConfigFeature();
const _user = createUserFeature();
const _tenant = createTenantFeature();
const _secrets = createSecretsFeature();
const _sessions = createSessionsFeature();
const _delivery = createDeliveryFeature();
const _files = createFilesFeature();
const _tierEngine = tierEngineFeature;
const _capCounter = capCounterFeature;
const _complianceProfiles = createComplianceProfilesFeature();
const _dataRetention = createDataRetentionFeature();
const _userDataRights = createUserDataRightsFeature();
const _textContent = createTextContentFeature();
const _templateResolver = createTemplateResolverFeature();
const _customFields = customFieldsFeature;

export const configValueTable = buildDrizzleTable("config-value", _config.entities["config-value"]!);
export const userTable = buildDrizzleTable("user", _user.entities["user"]!);
export const tenantTable = buildDrizzleTable("tenant", _tenant.entities["tenant"]!);
export const tenantMembershipTable = buildDrizzleTable("tenant-membership", _tenant.entities["tenant-membership"]!);
export const tenantInvitationTable = buildDrizzleTable("tenant-invitation", _tenant.entities["tenant-invitation"]!);
export const tenantSecretTable = buildDrizzleTable("tenant-secret", _secrets.entities["tenant-secret"]!);
export const userSessionTable = buildDrizzleTable("user-session", _sessions.entities["user-session"]!);
export const notificationPreferenceTable = buildDrizzleTable("notification-preference", _delivery.entities["notification-preference"]!);
export const fileRefTable = buildDrizzleTable("fileRef", _files.entities["fileRef"]!);
export const tierAssignmentTable = buildDrizzleTable("tier-assignment", _tierEngine.entities["tier-assignment"]!);
export const capCounterTable = buildDrizzleTable("cap-counter", _capCounter.entities["cap-counter"]!);
export const tenantComplianceProfileTable = buildDrizzleTable("tenant-compliance-profile", _complianceProfiles.entities["tenant-compliance-profile"]!);
export const tenantRetentionOverrideTable = buildDrizzleTable("tenant-retention-override", _dataRetention.entities["tenant-retention-override"]!);
export const exportJobTable = buildDrizzleTable("export-job", _userDataRights.entities["export-job"]!);
export const exportDownloadTokenTable = buildDrizzleTable("export-download-token", _userDataRights.entities["export-download-token"]!);
export const downloadAttemptTable = buildDrizzleTable("download-attempt", _userDataRights.entities["download-attempt"]!);
export const textBlockTable = buildDrizzleTable("text-block", _textContent.entities["text-block"]!);
export const templateResourceTable = buildDrizzleTable("template-resource", _templateResolver.entities["template-resource"]!);
export const fieldDefinitionTable = buildDrizzleTable("field-definition", _customFields.entities["field-definition"]!);
export { deliveryAttemptsTable } from "@cosmicdrift/kumiko-bundled-features/delivery";
export { subscriptionsProjectionTable } from "@cosmicdrift/kumiko-bundled-features/billing-foundation";
export { jobRunsTable, jobRunLogsTable } from "@cosmicdrift/kumiko-bundled-features/jobs";
