import { describe, expect, test } from "bun:test";
import { mergeBunfig, renderBunfig, renderBunfigFiles, TEST_TIMEOUT_MS } from "../bunfig";

const HEADER = (variant: string): string =>
  `# Generated by kumiko-testing (${variant}) - do not edit, regenerate with \`kumiko-testing bunfig\`.
# bun ignores a [test] timeout key; the class budget is passed as --timeout by the runner scripts.
[test]
`;

describe("renderBunfig", () => {
  test("unit", () => {
    expect(renderBunfig("unit")).toBe(`${HEADER("unit")}preload = [
  "@cosmicdrift/kumiko-testing/preload/temporal",
  "@cosmicdrift/kumiko-testing/preload/scrub-env",
]
pathIgnorePatterns = [
  "**/*.integration.test.ts",
  "**/*.real.test.ts",
  "**/*.test.tsx",
  "**/e2e/**",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/dist/**",
]
`);
  });

  test("integration", () => {
    expect(renderBunfig("integration")).toBe(`${HEADER("integration")}preload = [
  "@cosmicdrift/kumiko-testing/preload/temporal",
  "@cosmicdrift/kumiko-testing/preload/env",
]
pathIgnorePatterns = [
  "**/*.real.test.ts",
  "**/e2e/**",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/dist/**",
]
`);
  });

  test("real", () => {
    expect(renderBunfig("real")).toBe(`${HEADER("real")}preload = [
  "@cosmicdrift/kumiko-testing/preload/temporal",
  "@cosmicdrift/kumiko-testing/preload/real",
]
pathIgnorePatterns = [
  "**/*.integration.test.ts",
  "**/e2e/**",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/dist/**",
]
`);
  });

  test("dom unit runs *.test.tsx and adds the dom preload", () => {
    expect(renderBunfig("unit", { dom: true })).toBe(`${HEADER("dom")}preload = [
  "@cosmicdrift/kumiko-testing/preload/temporal",
  "@cosmicdrift/kumiko-testing/preload/scrub-env",
  "./test-setup/dom.preload.ts",
]
pathIgnorePatterns = [
  "**/*.integration.test.ts",
  "**/*.real.test.ts",
  "**/e2e/**",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/dist/**",
]
`);
  });

  test("coverage adds the lcov block with a per-variant directory", () => {
    expect(renderBunfig("integration", { coverage: true })).toBe(
      `${HEADER("integration")}preload = [
  "@cosmicdrift/kumiko-testing/preload/temporal",
  "@cosmicdrift/kumiko-testing/preload/env",
]
coverage = true
coverageReporter = ["lcov"]
coverageDir = "coverage/integration"
coveragePathIgnorePatterns = [
  "**/scripts/**",
  "**/bin/**",
]
pathIgnorePatterns = [
  "**/*.real.test.ts",
  "**/e2e/**",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/dist/**",
]
`,
    );
    expect(renderBunfig("unit", { dom: true, coverage: true })).toContain(
      'coverageDir = "coverage/dom"',
    );
  });

  test("install linker renders an [install] block between the header and [test]", () => {
    const text = renderBunfig("unit", { install: { linker: "hoisted" } });
    expect(text).toContain(
      `${HEADER("unit").replace("[test]\n", "")}[install]\nlinker = "hoisted"\n\n[test]\n`,
    );
    const parsed = Bun.TOML.parse(text) as { install: Record<string, unknown> };
    expect(parsed.install).toEqual({ linker: "hoisted" });
  });

  test("dom on a non-unit variant is rejected", () => {
    expect(() => renderBunfig("integration", { dom: true })).toThrow(/only applies to the unit/);
    expect(() => renderBunfig("real", { dom: true })).toThrow(/only applies to the unit/);
  });

  test("output is deterministic and parses as TOML without timeout or concurrency keys", () => {
    for (const variant of ["unit", "integration", "real"] as const) {
      const text = renderBunfig(variant, { coverage: true });
      expect(renderBunfig(variant, { coverage: true })).toBe(text);
      const parsed = Bun.TOML.parse(text) as { test: Record<string, unknown> };
      expect(Object.keys(parsed.test)).not.toContain("timeout");
      expect(Object.keys(parsed.test)).not.toContain("concurrency");
      expect(parsed.test["preload"]).toBeArray();
    }
  });
});

describe("renderBunfigFiles", () => {
  test("writes the three variants, plus the dom config only on request", () => {
    expect(Object.keys(renderBunfigFiles())).toEqual([
      "bunfig.toml",
      "bunfig.integration.toml",
      "bunfig.real.toml",
    ]);
    const withDom = renderBunfigFiles({ dom: true });
    expect(Object.keys(withDom)).toEqual([
      "bunfig.toml",
      "bunfig.integration.toml",
      "bunfig.real.toml",
      "bunfig.dom.toml",
    ]);
    expect(withDom["bunfig.toml"]).toContain('"**/*.test.tsx"');
    expect(withDom["bunfig.dom.toml"]).not.toContain('"**/*.test.tsx"');
  });

  test("install applies to every generated file", () => {
    for (const content of Object.values(
      renderBunfigFiles({ dom: true, install: { linker: "hoisted" } }),
    )) {
      expect(content).toContain('[install]\nlinker = "hoisted"');
    }
  });
});

// Excerpts of real, currently-committed bunfig.toml files (read-only, not
// modified by this fix) — kumiko-framework#3120's actual failure mode: every
// one of these apps sets [install.scopes] (private registry token) and a
// [test] key the template never emits (concurrency, at minimum).
const PHRONEXSIS_BUNFIG = `[install]
linker = "hoisted"

[install.scopes]
"@cosmicdriftgamestudio" = { url = "https://npm.pkg.github.com", token = "$GITHUB_TOKEN" }

[test]
concurrency = 8
pathIgnorePatterns = [
  "**/e2e/**",
  "**/*.test.tsx",
  "**/*.spec.ts",
  "**/dist/**",
]
`;

const SOLON_BUNFIG = `[install]
linker = "hoisted"

[install.scopes]
"@cosmicdriftgamestudio" = { url = "https://npm.pkg.github.com", token = "$GITHUB_TOKEN" }

[test]
concurrency = 8
pathIgnorePatterns = ["**/e2e/**", "**/*.spec.ts", "**/dist/**"]
`;

// bunfig.coverage.toml (phronexsis, publicstatus, money-horse, kumiko-studio):
// the real, committed [test].coverageThreshold key, which renderBunfig never emits.
const COVERAGE_BUNFIG = `[test]
coverage = true
coverageReporter = ["text"]
coverageThreshold = { functions = 0.95, lines = 0.85, statements = 0.9 }
coveragePathIgnorePatterns = [
  "**/node_modules/**",
]
`;

describe("mergeBunfig", () => {
  test("a freshly generated file merges with itself and needs no foreign block", () => {
    const generated = renderBunfig("unit");
    const result = mergeBunfig(generated, generated);
    expect(result).toEqual({ ok: true, content: generated });
  });

  test("keeps a section the template doesn't manage, e.g. a private-registry scope", () => {
    const generated = renderBunfig("unit", { install: { linker: "hoisted" } });
    const existing = `${generated}\n[install.scopes]\n"@cosmicdriftgamestudio" = { token = "$GITHUB_TOKEN" }\n`;
    const result = mergeBunfig(generated, existing);
    expect(result.ok).toBe(true);
    expect(result.ok && result.content).toContain(generated);
    expect(result.ok && result.content).toContain(
      '[install.scopes]\n"@cosmicdriftgamestudio" = { token = "$GITHUB_TOKEN" }',
    );
  });

  test("real phronexsis bunfig.toml: install.scopes preserved, concurrency named and blocked", () => {
    const result = mergeBunfig(
      renderBunfig("unit", { install: { linker: "hoisted" } }),
      PHRONEXSIS_BUNFIG,
    );
    expect(result).toEqual({ ok: false, unknownKeys: [{ section: "test", key: "concurrency" }] });
  });

  test("real solon bunfig.toml: same unmanaged concurrency key", () => {
    const result = mergeBunfig(
      renderBunfig("unit", { install: { linker: "hoisted" } }),
      SOLON_BUNFIG,
    );
    expect(result).toEqual({ ok: false, unknownKeys: [{ section: "test", key: "concurrency" }] });
  });

  test("a key the template doesn't emit inside [test] is named, not silently dropped", () => {
    const generated = renderBunfig("unit");
    const existing = generated.replace("[test]\n", "[test]\ntimeout = 15000\n");
    const result = mergeBunfig(generated, existing);
    expect(result.ok).toBe(false);
    expect(result.ok || result.unknownKeys).toEqual([{ section: "test", key: "timeout" }]);
  });

  test("does not flag the template's own [install]/[test] keys", () => {
    const generated = renderBunfig("unit", { install: { linker: "hoisted" }, coverage: true });
    expect(mergeBunfig(generated, generated)).toEqual({ ok: true, content: generated });
  });

  test("a run without --install keeps an existing [install] block instead of dropping it", () => {
    const generated = renderBunfig("unit");
    const existing = `${generated}[install]\nlinker = "hoisted"\n\n`;
    const result = mergeBunfig(generated, existing);
    expect(result.ok).toBe(true);
    expect(result.ok && result.content).toContain('[install]\nlinker = "hoisted"');
  });

  test("real *.coverage.toml: coverageThreshold is named, not silently dropped", () => {
    const generated = renderBunfig("integration", { coverage: true });
    const result = mergeBunfig(generated, COVERAGE_BUNFIG);
    expect(result).toEqual({
      ok: false,
      unknownKeys: [{ section: "test", key: "coverageThreshold" }],
    });
  });

  test("a top-level key before the first header (e.g. bun's own smol/telemetry) is named, not silently dropped", () => {
    const generated = renderBunfig("unit");
    const existing = `smol = true\ntelemetry = false\n${generated}`;
    const result = mergeBunfig(generated, existing);
    expect(result).toEqual({
      ok: false,
      unknownKeys: [
        { section: "", key: "smol" },
        { section: "", key: "telemetry" },
      ],
    });
  });

  test("the generated head (comments, no top-level keys) round-trips without a foreign block", () => {
    const generated = renderBunfig("unit", { install: { linker: "hoisted" } });
    const result = mergeBunfig(generated, generated);
    expect(result).toEqual({ ok: true, content: generated });
    expect(result.ok && result.content.startsWith("# Generated by kumiko-testing")).toBe(true);
  });
});

describe("TEST_TIMEOUT_MS", () => {
  test("unit keeps the bun default, integration and dom keep the repo budget", () => {
    expect(TEST_TIMEOUT_MS).toEqual({ unit: 5000, integration: 15000, dom: 15000, real: 120000 });
  });
});
