import { describe, expect, test } from "bun:test";
import { renderBunfig, renderBunfigFiles, TEST_TIMEOUT_MS } from "../bunfig";

const HEADER = (variant: string): string =>
  `# Generated by kumiko-testing (${variant}) - do not edit, regenerate with \`kumiko-testing bunfig\`.
# bun ignores a [test] timeout key; the class budget is passed as --timeout by the runner scripts.
[test]
`;

describe("renderBunfig", () => {
  test("unit", () => {
    expect(renderBunfig("unit")).toBe(`${HEADER("unit")}preload = [
  "@cosmicdrift/kumiko-testing/preload/temporal",
  "@cosmicdrift/kumiko-testing/preload/scrub-env",
]
pathIgnorePatterns = [
  "**/*.integration.test.ts",
  "**/*.real.test.ts",
  "**/*.test.tsx",
  "**/e2e/**",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/dist/**",
]
`);
  });

  test("integration", () => {
    expect(renderBunfig("integration")).toBe(`${HEADER("integration")}preload = [
  "@cosmicdrift/kumiko-testing/preload/temporal",
  "@cosmicdrift/kumiko-testing/preload/env",
]
pathIgnorePatterns = [
  "**/*.real.test.ts",
  "**/e2e/**",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/dist/**",
]
`);
  });

  test("real", () => {
    expect(renderBunfig("real")).toBe(`${HEADER("real")}preload = [
  "@cosmicdrift/kumiko-testing/preload/temporal",
  "@cosmicdrift/kumiko-testing/preload/real",
]
pathIgnorePatterns = [
  "**/*.integration.test.ts",
  "**/e2e/**",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/dist/**",
]
`);
  });

  test("dom unit runs *.test.tsx and adds the dom preload", () => {
    expect(renderBunfig("unit", { dom: true })).toBe(`${HEADER("dom")}preload = [
  "@cosmicdrift/kumiko-testing/preload/temporal",
  "@cosmicdrift/kumiko-testing/preload/scrub-env",
  "./test-setup/dom.preload.ts",
]
pathIgnorePatterns = [
  "**/*.integration.test.ts",
  "**/*.real.test.ts",
  "**/e2e/**",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/dist/**",
]
`);
  });

  test("coverage adds the lcov block with a per-variant directory", () => {
    expect(renderBunfig("integration", { coverage: true })).toBe(
      `${HEADER("integration")}preload = [
  "@cosmicdrift/kumiko-testing/preload/temporal",
  "@cosmicdrift/kumiko-testing/preload/env",
]
coverage = true
coverageReporter = ["lcov"]
coverageDir = "coverage/integration"
coveragePathIgnorePatterns = [
  "**/scripts/**",
  "**/bin/**",
]
pathIgnorePatterns = [
  "**/*.real.test.ts",
  "**/e2e/**",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/dist/**",
]
`,
    );
    expect(renderBunfig("unit", { dom: true, coverage: true })).toContain(
      'coverageDir = "coverage/dom"',
    );
  });

  test("install linker renders an [install] block between the header and [test]", () => {
    const text = renderBunfig("unit", { install: { linker: "hoisted" } });
    expect(text).toContain(
      `${HEADER("unit").replace("[test]\n", "")}[install]\nlinker = "hoisted"\n\n[test]\n`,
    );
    const parsed = Bun.TOML.parse(text) as { install: Record<string, unknown> };
    expect(parsed.install).toEqual({ linker: "hoisted" });
  });

  test("dom on a non-unit variant is rejected", () => {
    expect(() => renderBunfig("integration", { dom: true })).toThrow(/only applies to the unit/);
    expect(() => renderBunfig("real", { dom: true })).toThrow(/only applies to the unit/);
  });

  test("output is deterministic and parses as TOML without timeout or concurrency keys", () => {
    for (const variant of ["unit", "integration", "real"] as const) {
      const text = renderBunfig(variant, { coverage: true });
      expect(renderBunfig(variant, { coverage: true })).toBe(text);
      const parsed = Bun.TOML.parse(text) as { test: Record<string, unknown> };
      expect(Object.keys(parsed.test)).not.toContain("timeout");
      expect(Object.keys(parsed.test)).not.toContain("concurrency");
      expect(parsed.test["preload"]).toBeArray();
    }
  });
});

describe("renderBunfigFiles", () => {
  test("writes the three variants, plus the dom config only on request", () => {
    expect(Object.keys(renderBunfigFiles())).toEqual([
      "bunfig.toml",
      "bunfig.integration.toml",
      "bunfig.real.toml",
    ]);
    const withDom = renderBunfigFiles({ dom: true });
    expect(Object.keys(withDom)).toEqual([
      "bunfig.toml",
      "bunfig.integration.toml",
      "bunfig.real.toml",
      "bunfig.dom.toml",
    ]);
    expect(withDom["bunfig.toml"]).toContain('"**/*.test.tsx"');
    expect(withDom["bunfig.dom.toml"]).not.toContain('"**/*.test.tsx"');
  });

  test("install applies to every generated file", () => {
    for (const content of Object.values(
      renderBunfigFiles({ dom: true, install: { linker: "hoisted" } }),
    )) {
      expect(content).toContain('[install]\nlinker = "hoisted"');
    }
  });
});

describe("TEST_TIMEOUT_MS", () => {
  test("unit keeps the bun default, integration and dom keep the repo budget", () => {
    expect(TEST_TIMEOUT_MS).toEqual({ unit: 5000, integration: 15000, dom: 15000, real: 120000 });
  });
});
