import type { NavIconKey } from "@cosmicdrift/kumiko-framework/ui-types";
import {
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Building,
  Calculator,
  CalendarDays,
  Check,
  ClipboardList,
  Coins,
  Copy,
  CreditCard,
  Download,
  FileText,
  Folder,
  FolderOpen,
  Gauge,
  Hash,
  Home,
  KeyRound,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  Link,
  List,
  Lock,
  Mail,
  Package,
  Palette,
  PiggyBank,
  Plus,
  Receipt,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Sparkles,
  Table,
  Tag,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  Wallet,
  Wand2,
  X,
} from "lucide-react";

// Buttons resolve icons through the same map, importing it from the nav layout module would couple them to the sidebar.
export const NAV_ICONS = {
  dashboard: LayoutDashboard,
  "layout-grid": LayoutGrid,
  "book-open": BookOpen,
  "clipboard-list": ClipboardList,
  package: Package,
  gauge: Gauge,
  list: List,
  table: Table,
  layers: Layers,
  building: Building,
  calculator: Calculator,
  wallet: Wallet,
  coins: Coins,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  chart: LineChart,
  "bar-chart": BarChart3,
  trending: TrendingUp,
  sparkles: Sparkles,
  wand: Wand2,
  calendar: CalendarDays,
  file: FileText,
  folder: Folder,
  "folder-open": FolderOpen,
  home: Home,
  bell: Bell,
  shield: Shield,
  "shield-check": ShieldCheck,
  send: Send,
  settings: Settings,
  users: Users,
  user: User,
  search: Search,
  tag: Tag,
  key: KeyRound,
  link: Link,
  palette: Palette,
  share: Share2,
  server: Server,
  mail: Mail,
  lock: Lock,
  hash: Hash,
  download: Download,
  upload: Upload,
  rocket: Rocket,
  // Was imported but never registered — `icon: "plus"` silently fell back.
  plus: Plus,
  languages: Languages,
  trash: Trash2,
  x: X,
  check: Check,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  copy: Copy,
} as const satisfies Readonly<Record<NavIconKey, typeof Folder>>;
